import fs from "fs";
import path from "path";
import type { Collection, Db, ObjectId } from "mongodb";
import { computeMigrationChecksum } from "./MigrationTracker.js";

export type MongoMigrationRow = {
  id?: string;
  name: string;
  batch: number;
  checksum: string | null;
  run_at?: string;
};

type ResolvedMigrationFile = {
  fileName: string;
  filePath: string;
  relinked: boolean;
};

const MIGRATIONS_COLLECTION = "migrations";
const HISTORY_KIND = "history";
const LOCK_DOC_ID = "__eloquent_migration_lock__";

const AUTO_GENERATED_MIGRATION_RE =
  /^\d+_(create|update)_[A-Za-z0-9_]+_table\.(ts|js)$/;
const AUTO_GENERATED_CREATE_MIGRATION_RE =
  /^\d+_create_([A-Za-z0-9_]+)_table\.(ts|js)$/;

type MigrationHistoryDoc = {
  _id?: string | ObjectId;
  kind: "history";
  name: string;
  batch: number;
  checksum?: string | null;
  run_at?: Date | string;
};

type MigrationDoc = {
  _id?: string | ObjectId;
  kind?: "history" | "lock";
  owner?: string;
  name?: string;
  batch?: number;
  checksum?: string | null;
  run_at?: Date | string;
};

function migrationsCollection(db: Db): Collection<MigrationDoc> {
  return db.collection<MigrationDoc>(MIGRATIONS_COLLECTION);
}

function isCollectionAlreadyExistsError(error: unknown): boolean {
  const message = error instanceof Error ? error.message : String(error);
  return /already exists/i.test(message);
}

function isSafeIndexError(error: unknown): boolean {
  const message = error instanceof Error ? error.message : String(error);
  return (
    /already exists/i.test(message) ||
    /index options conflict/i.test(message) ||
    /equivalent index already exists/i.test(message)
  );
}

async function createCollectionIfMissing(db: Db, name: string): Promise<void> {
  try {
    await db.createCollection(name);
  } catch (error) {
    if (!isCollectionAlreadyExistsError(error)) {
      throw error;
    }
  }
}

async function createIndexIfMissing(
  db: Db,
  keys: Record<string, 1 | -1>,
  options: Record<string, unknown>
): Promise<void> {
  try {
    await migrationsCollection(db).createIndex(keys, options);
  } catch (error) {
    if (!isSafeIndexError(error)) {
      throw error;
    }
  }
}

function logicalMigrationName(fileName: string): string {
  return fileName.replace(/^\d+_/, "");
}

function isGeneratedMigrationFile(fileName: string): boolean {
  return AUTO_GENERATED_MIGRATION_RE.test(fileName);
}

function autoGeneratedCreateCollectionName(fileName: string): string | null {
  const match = AUTO_GENERATED_CREATE_MIGRATION_RE.exec(fileName);
  return match?.[1] ?? null;
}

function findMatchingMigrationFile(
  migrationsDir: string,
  fileName: string
): ResolvedMigrationFile | null {
  const exactPath = path.join(migrationsDir, fileName);
  if (fs.existsSync(exactPath)) {
    return {
      fileName,
      filePath: exactPath,
      relinked: false,
    };
  }

  if (!isGeneratedMigrationFile(fileName) || !fs.existsSync(migrationsDir)) {
    return null;
  }

  const logicalName = logicalMigrationName(fileName);
  const candidates = fs
    .readdirSync(migrationsDir)
    .filter((entry) => entry.endsWith(".ts") || entry.endsWith(".js"))
    .filter((entry) => isGeneratedMigrationFile(entry))
    .filter((entry) => logicalMigrationName(entry) === logicalName);

  if (candidates.length !== 1) {
    return null;
  }

  return {
    fileName: candidates[0],
    filePath: path.join(migrationsDir, candidates[0]),
    relinked: true,
  };
}

function normalizeRunAt(value: unknown): string | undefined {
  if (value instanceof Date) {
    return value.toISOString();
  }
  if (typeof value === "string") {
    return value;
  }
  return undefined;
}

async function collectionExists(db: Db, collectionName: string): Promise<boolean> {
  const rows = await db
    .listCollections({ name: collectionName }, { nameOnly: true })
    .toArray();
  return rows.length > 0;
}

async function updateMigrationChecksum(
  db: Db,
  migrationName: string,
  checksum: string
): Promise<void> {
  await migrationsCollection(db).updateOne(
    { kind: HISTORY_KIND, name: migrationName },
    { $set: { checksum } }
  );
}

async function relinkAppliedMigration(
  db: Db,
  previousName: string,
  nextName: string,
  checksum: string
): Promise<void> {
  await migrationsCollection(db).updateOne(
    { kind: HISTORY_KIND, name: previousName },
    { $set: { name: nextName, checksum } }
  );
}

async function tryPruneStaleGeneratedCreateMigration(
  db: Db,
  migrationName: string
): Promise<boolean> {
  const collectionName = autoGeneratedCreateCollectionName(migrationName);
  if (!collectionName) return false;

  const exists = await collectionExists(db, collectionName);
  if (exists) return false;

  await deleteAppliedMigration(db, migrationName);
  console.warn(
    `Pruned stale migration history entry "${migrationName}" (collection "${collectionName}" not found).`
  );
  return true;
}

export async function ensureMigrationCollection(db: Db): Promise<void> {
  await createCollectionIfMissing(db, MIGRATIONS_COLLECTION);
  await createIndexIfMissing(
    db,
    { name: 1 },
    { unique: true, sparse: true, name: "migrations_name_unique" }
  );
  await createIndexIfMissing(
    db,
    { batch: 1, run_at: 1 },
    { name: "migrations_batch_run_at_idx" }
  );
}

export async function acquireMigrationLock(db: Db, owner: string): Promise<void> {
  const collection = migrationsCollection(db);
  const existing = await collection.findOne<{ owner?: string }>({
    _id: LOCK_DOC_ID,
    kind: "lock",
  });

  if (!existing) {
    try {
      await collection.insertOne({
        _id: LOCK_DOC_ID,
        kind: "lock",
        owner,
        run_at: new Date(),
      });
      return;
    } catch {
      // Another process may have inserted first. Continue to verify owner.
    }
  }

  const lockState = await collection.findOne<{ owner?: string }>({
    _id: LOCK_DOC_ID,
    kind: "lock",
  });
  if (lockState?.owner === owner) {
    return;
  }

  throw new Error("Another migration process is already running.");
}

export async function releaseMigrationLock(db: Db, owner: string): Promise<void> {
  await migrationsCollection(db).deleteOne({
    _id: LOCK_DOC_ID,
    kind: "lock",
    owner,
  });
}

export async function readAppliedMigrations(db: Db): Promise<MongoMigrationRow[]> {
  const docs = (await migrationsCollection(db)
    .find({ kind: HISTORY_KIND })
    .sort({ batch: 1, run_at: 1, _id: 1 })
    .toArray()) as MigrationHistoryDoc[];

  return docs.map((doc) => ({
    id: doc._id === undefined || doc._id === null ? undefined : String(doc._id),
    name: doc.name,
    batch: Number(doc.batch ?? 0),
    checksum: doc.checksum ?? null,
    run_at: normalizeRunAt(doc.run_at),
  }));
}

export async function readLastBatch(db: Db): Promise<number> {
  const row = (await migrationsCollection(db)
    .find({ kind: HISTORY_KIND })
    .sort({ batch: -1, _id: -1 })
    .limit(1)
    .next()) as MigrationHistoryDoc | null;

  return row?.batch ? Number(row.batch) : 0;
}

export async function recordAppliedMigration(
  db: Db,
  fileName: string,
  batch: number,
  checksum: string
): Promise<void> {
  await migrationsCollection(db).insertOne({
    kind: HISTORY_KIND,
    name: fileName,
    batch,
    checksum,
    run_at: new Date(),
  });
}

export async function deleteAppliedMigration(
  db: Db,
  fileName: string
): Promise<void> {
  await migrationsCollection(db).deleteOne({
    kind: HISTORY_KIND,
    name: fileName,
  });
}

async function backfillMissingChecksums(
  db: Db,
  rows: MongoMigrationRow[],
  migrationsDir: string
): Promise<MongoMigrationRow[]> {
  const updatedRows: MongoMigrationRow[] = [];

  for (const row of rows) {
    if (row.checksum) {
      updatedRows.push(row);
      continue;
    }

    const resolved = findMatchingMigrationFile(migrationsDir, row.name);
    if (!resolved) {
      const pruned = await tryPruneStaleGeneratedCreateMigration(db, row.name);
      if (pruned) continue;

      const createCollectionName = autoGeneratedCreateCollectionName(row.name);
      if (createCollectionName) {
        const exists = await collectionExists(db, createCollectionName);
        if (exists) {
          console.warn(
            `Keeping orphaned applied migration "${row.name}" because collection "${createCollectionName}" still exists.`
          );
          updatedRows.push(row);
          continue;
        }
      }

      throw new Error(
        `Applied migration "${row.name}" is missing from disk and cannot be checksum-validated.`
      );
    }

    const checksum = computeMigrationChecksum(resolved.filePath);
    if (resolved.relinked) {
      await relinkAppliedMigration(db, row.name, resolved.fileName, checksum);
      updatedRows.push({ ...row, name: resolved.fileName, checksum });
      continue;
    }

    await updateMigrationChecksum(db, row.name, checksum);
    updatedRows.push({ ...row, checksum });
  }

  return updatedRows;
}

export async function validateMigrationHistory(
  db: Db,
  migrationsDir: string
): Promise<MongoMigrationRow[]> {
  const rows = await readAppliedMigrations(db);
  const hydratedRows = await backfillMissingChecksums(db, rows, migrationsDir);
  const validatedRows: MongoMigrationRow[] = [];

  for (const row of hydratedRows) {
    const resolved = findMatchingMigrationFile(migrationsDir, row.name);
    if (!resolved) {
      const pruned = await tryPruneStaleGeneratedCreateMigration(db, row.name);
      if (pruned) {
        continue;
      }

      const createCollectionName = autoGeneratedCreateCollectionName(row.name);
      if (createCollectionName) {
        const exists = await collectionExists(db, createCollectionName);
        if (exists) {
          console.warn(
            `Keeping orphaned applied migration "${row.name}" because collection "${createCollectionName}" still exists.`
          );
          validatedRows.push(row);
          continue;
        }
      }

      throw new Error(`Applied migration "${row.name}" is missing from disk.`);
    }

    const currentChecksum = computeMigrationChecksum(resolved.filePath);
    if (resolved.relinked) {
      await relinkAppliedMigration(db, row.name, resolved.fileName, currentChecksum);
      row.name = resolved.fileName;
      row.checksum = currentChecksum;
      validatedRows.push(row);
      continue;
    }

    if (row.checksum !== currentChecksum) {
      throw new Error(
        `Migration checksum mismatch for "${row.name}". The applied migration file was modified after execution.`
      );
    }

    validatedRows.push(row);
  }

  return validatedRows;
}

export async function doesCollectionExist(
  db: Db,
  collectionName: string
): Promise<boolean> {
  return await collectionExists(db, collectionName);
}
