/**
 * 🧩 Auto-generated EloquentJS ORM Model
 * Model: Car
 * Table: cars
 * Mode: DEVELOPMENT
 * Generated at: 2025-11-04T18:10:33.503Z
 */

import { BaseModel } from "../../core/model/BaseModel";
import { MorphableMixin, MorphableBaseModel } from "../../core/model/BaseModel";
import { column, validate } from "../../core/schema/SchemaBlueprint";

/**
 * 🧩 Car Model
 * Auto-generated by EloquentJS ORM
 * Table: cars
 * Connection: process.env.DB_CONNECTION ?? "mysql"
 *
 * Features:
 * - Full ORM support (Hooks, Scopes, Cache, EagerLoading)
 * - Built-in Morph + Pivot Relations
 * - Auto-registered in MorphRegistry
 * - Supports schema validation, soft deletes, timestamps
 */

const MorphableBase = MorphableMixin(BaseModel);

export class Car extends MorphableBase implements MorphableBaseModel {
  /**
   * ⚙️ Table configuration
   */
  static tableName = "cars";
  static connectionName = process.env.DB_CONNECTION ?? "mysql";

  /** 🪄 Morph alias (used for morphTo / morphMany) */
  static morphAlias = "cars";

  /**
   * 🧠 Schema definition
   */
  static schema = {
    id: column("increments", undefined, { primary: true }),
    name: validate(column("string", 255), { required: true, min: 3 }),
    created_at: column("timestamp"),
    updated_at: column("timestamp"),

    /**
     * 🔗 RELATIONS — Uncomment & customize
     * -------------------------------------------------
     * // belongsTo example:
     * user: { kind: "relation", relation: "belongsTo", model: "User", options: { foreignKey: "user_id" } },
     *
     * // morphOne example:
     * image: { kind: "relation", relation: "morphOne", model: "Image", options: { morphName: "imageable" } },
     *
     * // morphMany example:
     * comments: { kind: "relation", relation: "morphMany", model: "Comment", options: { morphName: "commentable" } },
     *
     * // morphTo example:
     * commentable: { kind: "relation", relation: "morphTo", options: { morphName: "commentable" } },
     * -------------------------------------------------
     */
  };

  /**
   * 🧩 Optional MIXINS
   * Uncomment as needed
   *
   * // static timestamps = true;
   * // static softDeletes = true;
   * // static cacheEnabled = true;
   */

  /**
   * 🧪 Validation lifecycle hooks
   */
  static validationHooks = {
    beforeValidate: async (data: Record<string, unknown>) => {
      console.log(`🧩 [beforeValidate] Car`, data);
    },
    afterValidate: async (data: Record<string, unknown>) => {
      console.log(`✅ [afterValidate] Car`, data);
    },
  };

  /**
   * ⚙️ Custom validation rules
   */
  static customRules = {
    isUnique: async (value: unknown) => {
      // Example: Add uniqueness logic here
      return true;
    },
  };

  /**
   * 🪝 Model lifecycle events
   */
  
  static modelEvents = {
    beforeCreate: async (data: Record<string, unknown>) => {
      console.log(`🚀 [beforeCreate] Car`, data);
    },
    afterCreate: async (record: Record<string, unknown>) => {
      console.log(`✅ [afterCreate] Car created:`, record);
    },
    beforeUpdate: async (data: Record<string, unknown>) => {
      console.log(`🔄 [beforeUpdate] Car`, data);
    },
    afterUpdate: async (data: Record<string, unknown>) => {
      console.log(`💾 [afterUpdate] Car updated:`, data);
    },
    beforeDelete: async (id: number | string) => {
      console.log(`🗑️ [beforeDelete] Car`, id);
    },
    afterDelete: async (id: number | string) => {
      console.log(`✅ [afterDelete] Car`, id);
    },
  };

  constructor() {
    super("cars", process.env.DB_CONNECTION ?? "mysql");
  }
}
