/**
 * 🧩 Auto-generated EloquentJS ORM Model
 * Model: Post
 * Table: posts
 * Mode: DEVELOPMENT
 * Generated at: 2026-02-03T11:53:35.157Z
 */

import { SqlModel, ModelInstance } from "../../core/model/BaseModel";
import { column, validate } from "../../core/schema/SchemaBlueprint";

/**
 * 🧩 Post Model
 * Auto-generated by EloquentJS ORM
 * Table: posts
 * Connection: process.env.DB_CONNECTION ?? "mysql"
 *
 * Features:
 * - Full ORM support (Hooks, Scopes, Cache, EagerLoading)
 * - Built-in Morph + Pivot Relations
 * - Auto-registered in MorphRegistry
 * - Supports schema validation, soft deletes, timestamps
 */

type PostAttrs = {
  id?: number;
  name?: string;
  user_id?: number | null;
  created_at?: string | Date | null;
  updated_at?: string | Date | null;
};

export class Post extends SqlModel<PostAttrs> {
  /**
   * ⚙️ Table configuration
   */
  static tableName = "posts";
  static connectionName = process.env.DB_CONNECTION ?? "mysql";

  /** 🪄 Morph alias (used for morphTo / morphMany) */
  static morphAlias = "posts";

  /**
   * 🧠 Schema definition
   */
  static schema = {
    id: column("increments", undefined, { primary: true }),
    name: validate(column("string", 255), { required: true, min: 3 }),
    user_id: column("int", undefined, { notNull: true }),
    created_at: column("timestamp"),
    updated_at: column("timestamp"),

    author: {
      kind: "relation",
      relation: "belongsTo",
      model: "User",
      options: { foreignKey: "user_id" },
    },
    favoritedBy: {
      kind: "relation",
      relation: "belongsToMany",
      model: "User",
      options: {},
    },
    comments: {
      kind: "relation",
      relation: "morphMany",
      model: "Comment",
      options: { morphName: "commentable" },
    },

    /**
     * 🔗 RELATIONS — Uncomment & customize
     * -------------------------------------------------
     * // belongsTo example:
     * user: { kind: "relation", relation: "belongsTo", model: "User", options: { foreignKey: "user_id" } },
     *
     * // morphOne example:
     * image: { kind: "relation", relation: "morphOne", model: "Image", options: { morphName: "imageable" } },
     *
     * // morphMany example:
     * comments: { kind: "relation", relation: "morphMany", model: "Comment", options: { morphName: "commentable" } },
     *
     * // morphTo example:
     * commentable: { kind: "relation", relation: "morphTo", options: { morphName: "commentable" } },
     * -------------------------------------------------
     */
  };

  /**
   * 🧩 Optional MIXINS
   * Uncomment as needed
   *
   * // static timestamps = true;
   * // static softDeletes = true;
   * // static cacheEnabled = true;
   */

  /**
   * 🧪 Validation lifecycle hooks
   */
  static validationHooks = {
    beforeValidate: async (data: Record<string, unknown>) => {
      console.log(`🧩 [beforeValidate] Post`, data);
    },
    afterValidate: async (data: Record<string, unknown>) => {
      console.log(`✅ [afterValidate] Post`, data);
    },
  };

  /**
   * ⚙️ Custom validation rules
   */
  static customRules = {
    isUnique: async (value: unknown) => {
      // Example: Add uniqueness logic here
      return true;
    },
  };

  /**
   * 🪝 Model lifecycle events
   */
  static modelEvents = {
    beforeCreate: async (data: Record<string, unknown>) => {
      console.log(`🚀 [beforeCreate] Post`, data);
    },
    afterCreate: async (record: Record<string, unknown>) => {
      console.log(`✅ [afterCreate] Post created:`, record);
    },
    beforeUpdate: async (data: Record<string, unknown>) => {
      console.log(`🔄 [beforeUpdate] Post`, data);
    },
    afterUpdate: async (data: Record<string, unknown>) => {
      console.log(`💾 [afterUpdate] Post updated:`, data);
    },
    beforeDelete: async (id: number | string) => {
      console.log(`🗑️ [beforeDelete] Post`, id);
    },
    afterDelete: async (id: number | string) => {
      console.log(`✅ [afterDelete] Post`, id);
    },
  };

  constructor() {
    super("posts", process.env.DB_CONNECTION ?? "mysql");
  }
}

// Laravel-style typed attributes (user.email, user.name, etc.)
export interface Post extends ModelInstance<PostAttrs> {}
