/**
 * 🧩 Auto-generated EloquentJS ORM Model
 * Model: Prescription
 * Table: prescriptions
 * Mode: DEVELOPMENT
 * Generated at: 2025-11-21T15:59:07.765Z
 */

import { de } from "@faker-js/faker/.";
import { BaseModel } from "../../core/model/BaseModel";
import { column, validate } from "../../core/schema/SchemaBlueprint";

/**
 * 🧩 Prescription Model
 * Auto-generated by EloquentJS ORM
 * Table: prescriptions
 * Connection: process.env.DB_CONNECTION ?? "mysql"
 *
 * Features:
 * - Full ORM support (Hooks, Scopes, Cache, EagerLoading)
 * - Built-in Morph + Pivot Relations
 * - Auto-registered in MorphRegistry
 * - Supports schema validation, soft deletes, timestamps
 */

export class Prescription extends BaseModel {
  /**
   * ⚙️ Table configuration
   */
  static tableName = "prescriptions";
  static connectionName = process.env.DB_CONNECTION ?? "mysql";

  /** 🪄 Morph alias (used for morphTo / morphMany) */
  static morphAlias = "prescriptions";

  /**
   * 🧠 Schema definition
   */
  static schema = {
    id: column("increments", undefined, { primary: true }),
    name: validate(column("string", 255), { required: true, min: 3 }),
    created_at: column("timestamp"),
    updated_at: column("timestamp"),
    deleted_at: column("timestamp")

    /**
     * 🔗 RELATIONS — Uncomment & customize
     * -------------------------------------------------
     * // belongsTo example:
     * user: { kind: "relation", relation: "belongsTo", model: "User", options: { foreignKey: "user_id" } },
     *
     * // morphOne example:
     * image: { kind: "relation", relation: "morphOne", model: "Image", options: { morphName: "imageable" } },
     *
     * // morphMany example:
     * comments: { kind: "relation", relation: "morphMany", model: "Comment", options: { morphName: "commentable" } },
     *
     * // morphTo example:
     * commentable: { kind: "relation", relation: "morphTo", options: { morphName: "commentable" } },
     * -------------------------------------------------
     */
  };

  /**
   * 🧩 Optional MIXINS
   * Uncomment as needed
   */
   static timestamps = true;
  //  static softDeletes = true;
   static cacheEnabled = true;
  static eagerLoadingEnabled = true;
  

  /**
   * 🧪 Validation lifecycle hooks
   */
  static validationHooks = {
    beforeValidate: async (data: Record<string, unknown>) => {
      console.log(`🧩 [beforeValidate] Prescription`, data);
    },
    afterValidate: async (data: Record<string, unknown>) => {
      console.log(`✅ [afterValidate] Prescription`, data);
    },
  };

  /**
   * ⚙️ Custom validation rules
   */
  static customRules = {
    isUnique: async (value: unknown) => {
      // Example: Add uniqueness logic here
      return true;
    },
  };

  /**
   * 🪝 Model lifecycle events
   */
  static modelEvents = {
    beforeCreate: async (data: Record<string, unknown>) => {
      console.log(`🚀 [beforeCreate] Prescription`, data);
    },
    afterCreate: async (record: Record<string, unknown>) => {
      console.log(`✅ [afterCreate] Prescription created:`, record);
    },
    beforeUpdate: async (data: Record<string, unknown>) => {
      console.log(`🔄 [beforeUpdate] Prescription`, data);
    },
    afterUpdate: async (data: Record<string, unknown>) => {
      console.log(`💾 [afterUpdate] Prescription updated:`, data);
    },
    beforeDelete: async (id: number | string) => {
      console.log(`🗑️ [beforeDelete] Prescription`, id);
    },
    afterDelete: async (id: number | string) => {
      console.log(`✅ [afterDelete] Prescription`, id);
    },
  };

  constructor() {
    super("prescriptions", process.env.DB_CONNECTION ?? "mysql");
  }
}
