/**
 * 🧩 Auto-generated EloquentJS ORM Model
 * Model: Test
 * Table: tests
 * Mode: DEVELOPMENT
 * Generated at: 2025-11-08T14:48:02.194Z
 */

import { url } from "inspector";
import { BaseModel } from "../../core/model/BaseModel";
import { MorphableMixin, MorphableBaseModel } from "../../core/model/BaseModel";
import { column, validate } from "../../core/schema/SchemaBlueprint";

/**
 * 🧩 Test Model
 * Auto-generated by EloquentJS ORM
 * Table: tests
 * Connection: process.env.DB_CONNECTION ?? "mysql"
 *
 * Features:
 * - Full ORM support (Hooks, Scopes, Cache, EagerLoading)
 * - Built-in Morph + Pivot Relations
 * - Auto-registered in MorphRegistry
 * - Supports schema validation, soft deletes, timestamps
 */

const MorphableBase = MorphableMixin(BaseModel);

export class Test extends MorphableBase implements MorphableBaseModel {
  /**
   * ⚙️ Table configuration
   */
  static tableName = "tests";
  static connectionName = process.env.DB_CONNECTION ?? "mysql";

  /** 🪄 Morph alias (used for morphTo / morphMany) */
  static morphAlias = "tests";

  /**
   * 🧠 Schema definition
   */
  static schema = {
    id: column("increments", undefined, { primary: true }),
    name: validate(column("string", 255), { required: true, min: 3 }),
    description: validate(column("text"), { required: false }),
    image: validate(column("string", 255), { required: false }),
    url: validate(column("string", 255), { required: false }),
    created_at: column("timestamp"),
    updated_at: column("timestamp"),

    /**
     * 🔗 RELATIONS — Uncomment & customize
     * -------------------------------------------------
     * // belongsTo example:
     * user: { kind: "relation", relation: "belongsTo", model: "User", options: { foreignKey: "user_id" } },
     *
     * // morphOne example:
     * image: { kind: "relation", relation: "morphOne", model: "Image", options: { morphName: "imageable" } },
     *
     * // morphMany example:
     * comments: { kind: "relation", relation: "morphMany", model: "Comment", options: { morphName: "commentable" } },
     *
     * // morphTo example:
     * commentable: { kind: "relation", relation: "morphTo", options: { morphName: "commentable" } },
     * -------------------------------------------------
     */
  };

  /**
   * 🧩 Optional MIXINS
   * Uncomment as needed
   *
   * // static timestamps = true;
   * // static softDeletes = true;
   * // static cacheEnabled = true;
   */

  /**
   * 🧪 Validation lifecycle hooks
   */
  static validationHooks = {
    beforeValidate: async (data: Record<string, unknown>) => {
      console.log(`🧩 [beforeValidate] Test`, data);
    },
    afterValidate: async (data: Record<string, unknown>) => {
      console.log(`✅ [afterValidate] Test`, data);
    },
  };

  /**
   * ⚙️ Custom validation rules
   */
  static customRules = {
    isUnique: async (value: unknown) => {
      // Example: Add uniqueness logic here
      return true;
    },
  };

  /**
   * 🪝 Model lifecycle events
   */
  static modelEvents = {
    beforeCreate: async (data: Record<string, unknown>) => {
      console.log(`🚀 [beforeCreate] Test`, data);
    },
    afterCreate: async (record: Record<string, unknown>) => {
      console.log(`✅ [afterCreate] Test created:`, record);
    },
    beforeUpdate: async (data: Record<string, unknown>) => {
      console.log(`🔄 [beforeUpdate] Test`, data);
    },
    afterUpdate: async (data: Record<string, unknown>) => {
      console.log(`💾 [afterUpdate] Test updated:`, data);
    },
    beforeDelete: async (id: number | string) => {
      console.log(`🗑️ [beforeDelete] Test`, id);
    },
    afterDelete: async (id: number | string) => {
      console.log(`✅ [afterDelete] Test`, id);
    },
  };

  constructor() {
    super("tests", process.env.DB_CONNECTION ?? "mysql");
  }
}
