/**
 * 🧩 Auto-generated EloquentJS ORM Model
 * Model: User
 * Table: users
 * Mode: DEVELOPMENT
 * Generated at: 2026-03-02T09:56:07.328Z
 */

import { SqlModel, ModelInstance } from "../../core/model/BaseModel";
import { column, validate } from "../../core/schema/SchemaBlueprint";

/**
 * 🧩 User Model
 * Auto-generated by EloquentJS ORM
 * Table: users
 * Connection: process.env.DB_CONNECTION ?? "mysql"
 *
 * Features:
 * - Full ORM support (Hooks, Scopes, Cache, EagerLoading)
 * - Built-in Morph + Pivot Relations
 * - Auto-registered in MorphRegistry
 * - Supports schema validation, soft deletes, timestamps
 */

type UserAttrs = {
  id?: number | null;
  name?: string | null;
  created_at?: string | Date | null;
  updated_at?: string | Date | null;
};

export class User extends SqlModel<UserAttrs> {
  /**
   * ⚙️ Table configuration
   */
  static tableName = "users";
  static connectionName = process.env.DB_CONNECTION ?? "mysql";

  /** 🪄 Morph alias (used for morphTo / morphMany) */
  static morphAlias = "users";

  /**
   * 🧠 Schema definition
   */
  static schema = {
    id: column("increments", undefined, { primary: true }),
    name: validate(column("string", 255), { required: true, min: 3 }),
    created_at: column("timestamp"),
    updated_at: column("timestamp"),

    /**
     * 🔗 RELATIONS — Uncomment & customize
     * -------------------------------------------------
     * // belongsTo example:
     * user: { kind: "relation", relation: "belongsTo", model: "User", options: { foreignKey: "user_id" } },
     *
     * // morphOne example:
     * image: { kind: "relation", relation: "morphOne", model: "Image", options: { morphName: "imageable" } },
     *
     * // morphMany example:
     * comments: { kind: "relation", relation: "morphMany", model: "Comment", options: { morphName: "commentable" } },
     *
     * // morphTo example:
     * commentable: { kind: "relation", relation: "morphTo", options: { morphName: "commentable" } },
     * -------------------------------------------------
     */
  };

  /**
   * 🧩 Optional MIXINS
   * Uncomment as needed
   *
   * // static timestamps = true;
   * // static softDeletes = true;
   * // static cacheEnabled = true;
   */

  /**
   * 🧪 Validation lifecycle hooks
   */
  static validationHooks = {
    beforeValidate: async (data: Record<string, unknown>) => {
      console.log(`🧩 [beforeValidate] User`, data);
    },
    afterValidate: async (data: Record<string, unknown>) => {
      console.log(`✅ [afterValidate] User`, data);
    },
  };

  /**
   * ⚙️ Custom validation rules
   */
  static customRules = {
    isUnique: async (value: unknown) => {
      // Example: Add uniqueness logic here
      return true;
    },
  };

  /**
   * 🪝 Model lifecycle events
   */
  static modelEvents = {
    beforeCreate: async (data: Record<string, unknown>) => {
      console.log(`🚀 [beforeCreate] User`, data);
    },
    afterCreate: async (record: Record<string, unknown>) => {
      console.log(`✅ [afterCreate] User created:`, record);
    },
    beforeUpdate: async (data: Record<string, unknown>) => {
      console.log(`🔄 [beforeUpdate] User`, data);
    },
    afterUpdate: async (data: Record<string, unknown>) => {
      console.log(`💾 [afterUpdate] User updated:`, data);
    },
    beforeDelete: async (id: number | string) => {
      console.log(`🗑️ [beforeDelete] User`, id);
    },
    afterDelete: async (id: number | string) => {
      console.log(`✅ [afterDelete] User`, id);
    },
  };

  constructor() {
    super("users", process.env.DB_CONNECTION ?? "mysql");
  }
}

// Laravel-style typed attributes (user.email, user.name, etc.)
export interface User extends ModelInstance<UserAttrs> {}
