/**
 * 🧩 Auto-generated EloquentJS ORM Model
 * Model: Dev
 * Table: devs
 * Mode: TEST
 * Generated at: 2025-11-03T17:42:22.104Z
 */

import { BaseModel, MorphableMixin, MorphableBaseModel } from "../../../core/model/BaseModel";
import { column, validate } from "../../../core/schema/SchemaBlueprint";

/**
 * 🧩 Dev Model
 * Auto-generated by EloquentJS ORM
 * Table: devs
 * Connection: process.env.DB_CONNECTION ?? "mysql"
 *
 * Features:
 * - Full ORM support (Hooks, Scopes, Cache, EagerLoading)
 * - Supports Morph and Pivot Relations
 * - Ready for schema validation, soft deletes, and timestamps
 */
const ORMixin = MorphableMixin(BaseModel) ;
export class Dev extends ORMixin implements MorphableBaseModel {
  /**
   * ⚙️ Table configuration
   */
  static tableName = "devs";
  static connectionName = "mysql";

  /**
   * 🧠 Schema definition
   * Define columns, relations, and validation rules.
   */
  static schema = {
    id: column("increments", undefined, { primary: true }),
    name: validate(column("string", 255), { required: true, min: 3 }),
    created_at: column("timestamp"),
    updated_at: column("timestamp"),

    /**
     * 🔗 RELATIONS — Uncomment & customize as needed
     * -------------------------------------------------
     * All relation types supported by EloquentJS ORM:
     *
     * // 1️⃣ belongsTo
     * user: { kind: "relation", relation: "belongsTo", model: "User", options: { foreignKey: "user_id" } },
     *
     * // 2️⃣ hasOne
     * profile: { kind: "relation", relation: "hasOne", model: "Profile", options: { foreignKey: "user_id" } },
     *
     * // 3️⃣ hasMany
     * posts: { kind: "relation", relation: "hasMany", model: "Post", options: { foreignKey: "user_id" } },
     *
     * // 4️⃣ belongsToMany (auto pivot table support)
     * roles: { kind: "relation", relation: "belongsToMany", model: "Role" },
     *
     * // 5️⃣ morphOne
     * image: { kind: "relation", relation: "morphOne", model: "Image", options: { morphName: "imageable" } },
     *
     * // 6️⃣ morphMany
     * comments: { kind: "relation", relation: "morphMany", model: "Comment", options: { morphName: "commentable" } },
     *
     * // 7️⃣ morphTo
     * commentable: { kind: "relation", relation: "morphTo", options: { morphName: "commentable" } },
     * -------------------------------------------------
     */
  };

  /**
   * 🧩 Optional MIXINS
   * Uncomment these lines to enable common features:
   *
   * // 🕒 Timestamps
   * static timestamps = true;
   *
   * // 🧹 Soft Deletes
   * static softDeletes = true;
   *
   * // ⚡ Query Cache
   * static cacheEnabled = true;
   *
   * // 🔍 Scopes example
   * static scopes = {
   *   active: (query) => query.where("is_active", true),
   * };
   */

  /**
   * 🧪 Validation lifecycle hooks
   */
  static validationHooks = {
    beforeValidate: async (data: Record<string, unknown>) => {
      console.log("🧩 [beforeValidate] Dev", data);
    },
    afterValidate: async (data: Record<string, unknown>) => {
      console.log("✅ [afterValidate] Dev", data);
    },
  };

  /**
   * ⚙️ Custom validation rules (global + async supported)
   */
  static customRules = {
    isUnique: async (value: unknown) => {
      // Example: Add uniqueness logic here
      return true;
    },
  };

  /**
   * 🪝 Model lifecycle events
   */
  static modelEvents = {
    beforeCreate: async (data: Record<string, unknown>) => {
      console.log("🚀 [beforeCreate] Dev", data);
    },
    afterCreate: async (record: Record<string, unknown>) => {
      console.log("✅ [afterCreate] Dev created:", record);
    },
    beforeUpdate: async (data: Record<string, unknown>) => {
      console.log("🔄 [beforeUpdate] Dev", data);
    },
    afterUpdate: async (data: Record<string, unknown>) => {
      console.log("💾 [afterUpdate] Dev updated:", data);
    },
    beforeDelete: async (id: number | string) => {
      console.log("🗑️ [beforeDelete] Dev", id);
    },
    afterDelete: async (id: number | string) => {
      console.log("✅ [afterDelete] Dev", id);
    },
  };

  constructor() {
    super("devs", process.env.DB_CONNECTION ?? "mysql");
  }
}
