import { SqlModel, ModelInstance } from "{{coreImportPath}}";
import { column, validate } from "{{schemaImportPath}}";

/**
 * 🧩 {{ModelName}} Model
 * Auto-generated by EloquentJS ORM
 * Table: {{tableName}}
 * Connection: process.env.DB_CONNECTION ?? "mysql"
 *
 * Features:
 * - Full ORM support (Hooks, Scopes, Cache, EagerLoading)
 * - Built-in Morph + Pivot Relations
 * - Auto-registered in MorphRegistry
 * - Supports schema validation, soft deletes, timestamps
 */

type {{ModelName}}Attrs = {
{{attrsTypeBody}}
};

export class {{ModelName}} extends SqlModel<{{ModelName}}Attrs> {
  /**
   * ⚙️ Table configuration
   */
  static tableName = "{{tableName}}";
  static connectionName = process.env.DB_CONNECTION ?? "mysql";

  /** 🪄 Morph alias (used for morphTo / morphMany) */
  static morphAlias = "{{tableName}}";

  /**
   * 🧠 Schema definition
   */
  static schema = {
    id: column("increments", undefined, { primary: true }),
    name: validate(column("string", 255), { required: true, min: 3 }),
    created_at: column("timestamp"),
    updated_at: column("timestamp"),

    /**
     * 🔗 RELATIONS — Uncomment & customize
     * -------------------------------------------------
     * // belongsTo example:
     * user: { kind: "relation", relation: "belongsTo", model: "User", options: { foreignKey: "user_id" } },
     *
     * // morphOne example:
     * image: { kind: "relation", relation: "morphOne", model: "Image", options: { morphName: "imageable" } },
     *
     * // morphMany example:
     * comments: { kind: "relation", relation: "morphMany", model: "Comment", options: { morphName: "commentable" } },
     *
     * // morphTo example:
     * commentable: { kind: "relation", relation: "morphTo", options: { morphName: "commentable" } },
     * -------------------------------------------------
     */
  };

  /**
   * 🧩 Optional MIXINS
   * Uncomment as needed
   *
   * // static timestamps = true;
   * // static softDeletes = true;
   * // static cacheEnabled = true;
   */

  /**
   * 🧪 Validation lifecycle hooks
   */
  static validationHooks = {
    beforeValidate: async (data: Record<string, unknown>) => {
      console.log(`🧩 [beforeValidate] {{ModelName}}`, data);
    },
    afterValidate: async (data: Record<string, unknown>) => {
      console.log(`✅ [afterValidate] {{ModelName}}`, data);
    },
  };

  /**
   * ⚙️ Custom validation rules
   */
  static customRules = {
    isUnique: async (value: unknown) => {
      // Example: Add uniqueness logic here
      return true;
    },
  };

  /**
   * 🪝 Model lifecycle events
   */
  static modelEvents = {
    beforeCreate: async (data: Record<string, unknown>) => {
      console.log(`🚀 [beforeCreate] {{ModelName}}`, data);
    },
    afterCreate: async (record: Record<string, unknown>) => {
      console.log(`✅ [afterCreate] {{ModelName}} created:`, record);
    },
    beforeUpdate: async (data: Record<string, unknown>) => {
      console.log(`🔄 [beforeUpdate] {{ModelName}}`, data);
    },
    afterUpdate: async (data: Record<string, unknown>) => {
      console.log(`💾 [afterUpdate] {{ModelName}} updated:`, data);
    },
    beforeDelete: async (id: number | string) => {
      console.log(`🗑️ [beforeDelete] {{ModelName}}`, id);
    },
    afterDelete: async (id: number | string) => {
      console.log(`✅ [afterDelete] {{ModelName}}`, id);
    },
  };

  constructor() {
    super("{{tableName}}", process.env.DB_CONNECTION ?? "mysql");
  }
}

// Laravel-style typed attributes (user.email, user.name, etc.)
export interface {{ModelName}} extends ModelInstance<{{ModelName}}Attrs> {}
