import { {{modelBaseClass}}, ModelInstance } from "{{coreImportPath}}";
import { column, validate } from "{{schemaImportPath}}";

/**
 * {{ModelName}} model
 * Auto-generated by EloquentJS ORM.
 * Table: {{tableName}}
 * Connection: {{connectionDescription}}
 */
type {{ModelName}}Attrs = {
{{attrsTypeBody}}
};

export class {{ModelName}} extends {{modelBaseClass}}<{{ModelName}}Attrs> {
  static tableName = "{{tableName}}";
  static connectionName = {{connectionExpression}};

  // Used by morphTo/morphMany relations.
  static morphAlias = "{{tableName}}";

  static schema = {
    id: column("increments", undefined, { primary: true }),
    name: validate(column("string", 255), { required: true, min: 3 }),
    created_at: column("timestamp"),
    updated_at: column("timestamp"),

    /*
     * RELATIONS EXAMPLES (uncomment and adapt):
     * user: { kind: "relation", relation: "belongsTo", model: "User", options: { foreignKey: "user_id" } },
     * image: { kind: "relation", relation: "morphOne", model: "Image", options: { morphName: "imageable" } },
     * comments: { kind: "relation", relation: "morphMany", model: "Comment", options: { morphName: "commentable" } },
     * commentable: { kind: "relation", relation: "morphTo", options: { morphName: "commentable" } },
     */
  };

  /*
   * OPTIONAL MIXINS (uncomment as needed):
   * static timestamps = true;
   * static softDeletes = true;
   * static cacheEnabled = true;
   *
   * INSTANCE PERSISTENCE EXAMPLES
   * -------------------------------------------------
   *   const model = new {{ModelName}}();
   *   model.fill({ name: "Example" });
   *   await model.save();
   *   model.update({ name: "Example 2" });
   *   await model.save();
   *   await model.patch({ name: "Example 3" });
   * -------------------------------------------------
   */

  static validationHooks = {
    beforeValidate: async (data: Record<string, unknown>) => {
      console.log("[beforeValidate] {{ModelName}}", data);
    },
    afterValidate: async (data: Record<string, unknown>) => {
      console.log("[afterValidate] {{ModelName}}", data);
    },
  };

  static customRules = {
    isUnique: async (_value: unknown) => {
      // Example: add uniqueness logic here.
      return true;
    },
  };

  static modelEvents = {
    beforeCreate: async (data: Record<string, unknown>) => {
      console.log("[beforeCreate] {{ModelName}}", data);
    },
    afterCreate: async (record: Record<string, unknown> | null) => {
      console.log("[afterCreate] {{ModelName}} created:", record);
    },
    beforeUpdate: async (data: Record<string, unknown>) => {
      console.log("[beforeUpdate] {{ModelName}}", data);
    },
    afterUpdate: async (data: Record<string, unknown>) => {
      console.log("[afterUpdate] {{ModelName}} updated:", data);
    },
    beforeDelete: async (id: number | string) => {
      console.log("[beforeDelete] {{ModelName}}", id);
    },
    afterDelete: async (id: number | string) => {
      console.log("[afterDelete] {{ModelName}}", id);
    },
  };

  constructor() {
    super("{{tableName}}", {{connectionExpression}});
  }
}

export interface {{ModelName}} extends ModelInstance<{{ModelName}}Attrs> {}
