import fs from "fs";
import os from "os";
import path from "path";
import { dbConfig } from "../config/database";
import {
  NativeSqlMigrationLockStrategy,
  resetMigrationLockStrategy,
} from "../cli/utils/migrations/MigrationLockStrategy";
import {
  backfillMissingChecksums,
  doesMigrationTableExist,
  ensureMigrationTables,
  getAutoGeneratedCreateTableName,
  recordAppliedMigration,
  validateMigrationHistory,
} from "../cli/utils/migrations/MigrationTracker";
import type { DriverAdapter } from "../core/connection/DriverAdapter";
import type { ConnectionName } from "../core/connection/ConnectionFactory";

type MockAdapter = DriverAdapter & {
  query: jest.Mock;
  queryOne: jest.Mock;
  execute: jest.Mock;
};

function makeAdapter(name: ConnectionName): MockAdapter {
  const query = jest.fn();
  const queryOne = jest.fn();
  const execute = jest.fn();

  return {
    name,
    kind: "sql",
    query,
    queryOne,
    execute,
    insert: jest.fn(),
    placeholder: (index: number) => (name.includes("pg") ? `$${index}` : "?"),
    placeholders: (count: number, startIndex = 1) =>
      Array.from({ length: count }, (_, idx) =>
        name.includes("pg") ? `$${startIndex + idx}` : "?"
      ).join(", "),
    inClause: (field: string, values: unknown[], startIndex = 1) => ({
      sql: `${field} IN (${Array.from({ length: values.length }, () => "?").join(", ")})`,
      params: values,
      nextIndex: startIndex + values.length,
    }),
    wrapId: (id: string) => `\`${id}\``,
  };
}

describe("Branch coverage 100% - phase 4 migration tracker and locking edges", () => {
  let mysqlDriverBefore: string;

  beforeEach(() => {
    mysqlDriverBefore = dbConfig.connections.mysql.driver;
  });

  afterEach(() => {
    dbConfig.connections.mysql.driver = mysqlDriverBefore as any;
    resetMigrationLockStrategy();
    jest.restoreAllMocks();
  });

  test("ensureMigrationTables covers pg/sqlite checksum alter branches and unsupported driver error", async () => {
    const pg = makeAdapter("pg_test");
    pg.query.mockResolvedValueOnce([]); // checksum missing in pg
    pg.execute.mockResolvedValue(undefined);

    await expect(ensureMigrationTables(pg)).resolves.toBe("pg");
    expect(pg.query).toHaveBeenCalledWith(
      expect.stringContaining("FROM information_schema.columns"),
      ["migrations", "checksum"]
    );
    expect(
      pg.execute.mock.calls.some(([sql]) =>
        String(sql).includes("ADD COLUMN `checksum` VARCHAR(64)")
      )
    ).toBe(true);

    const sqlite = makeAdapter("sqlite_test");
    sqlite.query.mockResolvedValueOnce([{ name: "id" }]); // checksum missing in sqlite
    sqlite.execute.mockResolvedValue(undefined);

    await expect(ensureMigrationTables(sqlite)).resolves.toBe("sqlite");
    expect(
      sqlite.execute.mock.calls.some(([sql]) => String(sql).includes("ADD COLUMN `checksum` TEXT"))
    ).toBe(true);

    const mongo = makeAdapter("mongo");
    await expect(ensureMigrationTables(mongo)).rejects.toThrow(
      "Unsupported SQL driver for migrations: mongo"
    );

    const unknown = makeAdapter("sql_ghost" as ConnectionName);
    await expect(ensureMigrationTables(unknown)).rejects.toThrow(
      "Unsupported SQL driver for migrations: sql_ghost"
    );
  });

  test("doesMigrationTableExist covers pg and sqlite table lookup branches", async () => {
    const pg = makeAdapter("pg_test");
    pg.query.mockResolvedValueOnce([{ table_name: "migrations" }]);
    await expect(doesMigrationTableExist(pg, "migrations")).resolves.toBe(true);
    expect(pg.query).toHaveBeenCalledWith(expect.stringContaining("information_schema.tables"), [
      "migrations",
    ]);

    const sqlite = makeAdapter("sqlite_test");
    sqlite.query.mockResolvedValueOnce([]);
    await expect(doesMigrationTableExist(sqlite, "migrations")).resolves.toBe(false);
    expect(sqlite.query).toHaveBeenCalledWith(
      expect.stringContaining("FROM sqlite_master"),
      ["migrations"]
    );
  });

  test("recordAppliedMigration and getAutoGeneratedCreateTableName branches", async () => {
    const mysql = makeAdapter("mysql_test");
    mysql.execute.mockResolvedValue(undefined);

    await recordAppliedMigration(
      mysql,
      "20260308093000001_create_users_table.ts",
      7,
      "abc123checksum"
    );

    expect(mysql.execute).toHaveBeenCalledWith(
      expect.stringContaining("INSERT INTO `migrations`"),
      ["20260308093000001_create_users_table.ts", 7, "abc123checksum"]
    );

    expect(getAutoGeneratedCreateTableName("20260308093000001_create_users_table.ts")).toBe(
      "users"
    );
    expect(getAutoGeneratedCreateTableName("20260308093000002_update_users_table.ts")).toBeNull();
  });

  test("backfillMissingChecksums covers relink + prune + orphan-keep + missing-file error branches", async () => {
    const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "phase4-backfill-"));
    try {
      const mysql = makeAdapter("mysql_test");
      mysql.execute.mockResolvedValue(undefined);

      const oldName = "20260308093100001_create_comments_table.ts";
      const nextName = "20260308093199999_create_comments_table.ts";
      const nextPath = path.join(tempDir, nextName);
      fs.writeFileSync(nextPath, "export async function up() { return; }\n", "utf8");

      const relinked = await backfillMissingChecksums(
        mysql,
        [{ name: oldName, batch: 1, checksum: null }],
        tempDir
      );
      expect(relinked[0]?.name).toBe(nextName);
      expect(relinked[0]?.checksum).toHaveLength(64);
      expect(mysql.execute).toHaveBeenCalledWith(
        expect.stringContaining("SET `name` = ?, `checksum` = ?"),
        [nextName, expect.any(String), oldName]
      );

      mysql.query.mockImplementation(async (_sql: string, params?: unknown[]) => {
        const targetTable = params?.[0];
        if (targetTable === "staleonly") return [];
        if (targetTable === "orphankeep") return [{ Tables_in_test: "orphankeep" }];
        return [];
      });

      const staleOnly = await backfillMissingChecksums(
        mysql,
        [{ name: "20260308093200001_create_staleonly_table.ts", batch: 1, checksum: null }],
        tempDir
      );
      expect(staleOnly).toEqual([]);
      expect(mysql.execute).toHaveBeenCalledWith(
        expect.stringContaining("DELETE FROM `migrations` WHERE `name` = ?"),
        ["20260308093200001_create_staleonly_table.ts"]
      );

      const orphanKeep = await backfillMissingChecksums(
        mysql,
        [{ name: "20260308093300001_create_orphankeep_table.ts", batch: 1, checksum: null }],
        tempDir
      );
      expect(orphanKeep).toEqual([
        { name: "20260308093300001_create_orphankeep_table.ts", batch: 1, checksum: null },
      ]);

      await expect(
        backfillMissingChecksums(
          mysql,
          [{ name: "custom_manual_migration.ts", batch: 1, checksum: null }],
          tempDir
        )
      ).rejects.toThrow("cannot be checksum-validated");

      const jsOld = "20260308093500001_update_profiles_table.js";
      const jsNext = "20260308093599999_update_profiles_table.js";
      fs.writeFileSync(path.join(tempDir, jsNext), "module.exports.up = async () => {};\n", "utf8");

      const jsRelinked = await backfillMissingChecksums(
        mysql,
        [{ name: jsOld, batch: 1, checksum: null }],
        tempDir
      );
      expect(jsRelinked[0]?.name).toBe(jsNext);
      expect(jsRelinked[0]?.checksum).toHaveLength(64);
    } finally {
      fs.rmSync(tempDir, { recursive: true, force: true });
    }
  });

  test("backfillMissingChecksums covers second table-exists false branch after prune gate", async () => {
    const mysql = makeAdapter("mysql_test");
    const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "phase4-backfill-flip-"));
    try {
      let tableCheckCount = 0;
      mysql.query.mockImplementation(async (sql: string) => {
        if (!sql.startsWith("SHOW TABLES LIKE")) {
          throw new Error(`Unexpected SQL: ${sql}`);
        }
        tableCheckCount += 1;
        return tableCheckCount === 1 ? [{ Tables_in_test: "fliptable" }] : [];
      });

      await expect(
        backfillMissingChecksums(
          mysql,
          [{ name: "20260308093600001_create_fliptable_table.ts", batch: 1, checksum: null }],
          tempDir
        )
      ).rejects.toThrow("cannot be checksum-validated");
    } finally {
      fs.rmSync(tempDir, { recursive: true, force: true });
    }
  });

  test("validateMigrationHistory throws missing-file error after checksum hydration pass", async () => {
    const mysql = makeAdapter("mysql_test");
    const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "phase4-validate-missing-"));
    try {
      const missingUpdate = "20260308093400001_update_comments_table.ts";
      mysql.query.mockResolvedValueOnce([
        {
          id: 1,
          name: missingUpdate,
          batch: 2,
          checksum: "already-present-checksum",
          run_at: "2026-03-08",
        },
      ]);

      await expect(validateMigrationHistory(mysql, tempDir)).rejects.toThrow(
        `Applied migration "${missingUpdate}" is missing from disk.`
      );
    } finally {
      fs.rmSync(tempDir, { recursive: true, force: true });
    }
  });

  test("validateMigrationHistory covers second table-exists false branch before missing-disk throw", async () => {
    const mysql = makeAdapter("mysql_test");
    const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "phase4-validate-flip-"));
    try {
      const missingCreate = "20260308093700001_create_validationflip_table.ts";
      let tableCheckCount = 0;

      mysql.query.mockImplementation(async (sql: string) => {
        if (sql.includes("FROM `migrations`")) {
          return [
            {
              id: 1,
              name: missingCreate,
              batch: 1,
              checksum: "already-hydrated",
              run_at: "2026-03-08",
            },
          ];
        }
        if (sql.startsWith("SHOW TABLES LIKE")) {
          tableCheckCount += 1;
          return tableCheckCount === 1
            ? [{ Tables_in_test: "validationflip" }]
            : [];
        }
        throw new Error(`Unexpected SQL: ${sql}`);
      });

      await expect(validateMigrationHistory(mysql, tempDir)).rejects.toThrow(
        `Applied migration "${missingCreate}" is missing from disk.`
      );
    } finally {
      fs.rmSync(tempDir, { recursive: true, force: true });
    }
  });

  test("NativeSqlMigrationLockStrategy covers resolveDriver fallback and sqlite edge paths", async () => {
    const strategy = new NativeSqlMigrationLockStrategy();

    dbConfig.connections.mysql.driver = "mongo" as any;
    const mysqlByName = makeAdapter("mysql");
    mysqlByName.queryOne.mockResolvedValueOnce({ acquired: 1 });
    await expect(strategy.acquire(mysqlByName, "owner-fallback")).resolves.toBeUndefined();
    expect(mysqlByName.queryOne).toHaveBeenCalledWith(
      expect.stringContaining("GET_LOCK"),
      ["eloquentjs:migrate:mysql"]
    );

    const connections = dbConfig.connections as unknown as Record<string, { driver: string }>;
    const previousEmpty = connections[""];
    connections[""] = { driver: "pg" };

    try {
      const pgBlankName = makeAdapter("" as ConnectionName);
      pgBlankName.queryOne.mockResolvedValueOnce({ acquired: true });
      await expect(strategy.acquire(pgBlankName, "owner-blank")).resolves.toBeUndefined();
      expect(pgBlankName.queryOne).toHaveBeenCalledWith(
        expect.stringContaining("pg_try_advisory_lock"),
        [1]
      );
    } finally {
      if (previousEmpty) {
        connections[""] = previousEmpty;
      } else {
        delete connections[""];
      }
    }

    const sqlite = makeAdapter("sqlite_test");
    sqlite.execute.mockRejectedValueOnce(new Error("sqlite-unknown-failure"));
    await expect(strategy.acquire(sqlite, "owner-sqlite")).rejects.toThrow(
      "sqlite-unknown-failure"
    );

    const sqliteBusyString = makeAdapter("sqlite_test");
    sqliteBusyString.execute.mockRejectedValueOnce("database is locked");
    await expect(strategy.acquire(sqliteBusyString, "owner-sqlite-busy")).rejects.toThrow(
      "Another migration process is already running."
    );

    const sqliteNoOwner = makeAdapter("sqlite_test");
    await expect(strategy.release(sqliteNoOwner, "owner-none")).resolves.toBeUndefined();

    const sqliteRollbackFail = makeAdapter("sqlite_test");
    sqliteRollbackFail.execute
      .mockResolvedValueOnce(undefined)
      .mockRejectedValueOnce(new Error("rollback-fail"));
    await strategy.acquire(sqliteRollbackFail, "owner-rollback");
    await expect(
      strategy.release(sqliteRollbackFail, "owner-rollback", { success: false })
    ).resolves.toBeUndefined();
  });
});
