import fs from "fs";
import os from "os";
import path from "path";

const passthroughChalk = {
  __esModule: true,
  default: {
    gray: (v: string) => v,
    yellow: (v: string) => v,
    cyan: (v: string) => v,
    green: (v: string) => v,
    greenBright: (v: string) => v,
    red: (v: string) => v,
    redBright: (v: string) => v,
  },
};

describe("Branch coverage 100% - phase 30 migrateFresh + migrateRollback edge closure", () => {
  afterEach(() => {
    jest.restoreAllMocks();
    jest.resetModules();
    jest.clearAllMocks();
    process.exitCode = 0;
  });

  test("migrateFresh default options path resolves connection and skips non-SQL driver", async () => {
    jest.resetModules();

    const db = {
      execute: jest.fn(async () => undefined),
      query: jest.fn(async () => []),
      wrapId: jest.fn((id: string) => `\`${id}\``),
    };

    const getAdapter = jest.fn(async () => db);
    const closeAllConnections = jest.fn(async () => undefined);
    const migrateRun = jest.fn(async () => undefined);
    const makeMigration = jest.fn(async () => undefined);
    const resolveConnectionName = jest.fn(() => "mongo" as any);

    jest.doMock("chalk", () => passthroughChalk);
    jest.doMock("readline", () => ({
      createInterface: () => ({
        question: (_prompt: string, cb: (answer: string) => void) => cb("y"),
        close: jest.fn(),
      }),
    }));
    jest.doMock("../core/connection/ConnectionFactory", () => ({
      getAdapter,
      closeAllConnections,
    }));
    jest.doMock("../core/connection/resolveConnectionName", () => ({
      resolveConnectionName,
    }));
    jest.doMock("../config/database", () => ({
      dbConfig: {
        connections: {
          mongo: { driver: "mongo" },
        },
      },
    }));
    jest.doMock("../cli/commands/migrateRun", () => ({
      migrateRun,
    }));
    jest.doMock("../cli/commands/makeMigration", () => ({
      makeMigration,
    }));

    const warnSpy = jest.spyOn(console, "warn").mockImplementation(() => undefined);
    const { migrateFresh } = await import("../cli/commands/migrateFresh");
    await migrateFresh();

    expect(resolveConnectionName).toHaveBeenCalledWith(undefined, { test: false });
    expect(getAdapter).toHaveBeenCalledWith("mongo");
    expect(warnSpy).toHaveBeenCalledWith(
      expect.stringContaining("Skipping non-SQL connection: mongo")
    );
    expect(makeMigration).not.toHaveBeenCalled();
    expect(migrateRun).toHaveBeenCalledWith(false, undefined, false, false, {
      connectionNames: ["mongo"],
      auditCommand: "migrate:fresh",
    });
    expect(closeAllConnections).toHaveBeenCalled();
  });

  test("migrateRollback default options path uses fallback driver and nullish id sort fallback", async () => {
    jest.resetModules();

    const root = fs.mkdtempSync(path.join(os.tmpdir(), "eloquent-phase30-rollback-"));
    const migrationsDir = path.join(root, "sqlite");
    fs.mkdirSync(migrationsDir, { recursive: true });

    const migrationA = "202603090001_update_users_table.ts";
    const migrationB = "202603090002_update_posts_table.ts";
    fs.writeFileSync(path.join(migrationsDir, migrationA), "// fixture", "utf8");
    fs.writeFileSync(path.join(migrationsDir, migrationB), "// fixture", "utf8");

    const db = {
      execute: jest.fn(async () => undefined),
      wrapId: jest.fn((id: string) => `\`${id}\``),
    };

    const getAdapter = jest.fn(async () => db);
    const closeAllConnections = jest.fn(async () => undefined);
    const resolveConnectionName = jest.fn(() => "sqlite" as any);
    const ensureMigrationTables = jest.fn(async () => undefined);
    const acquireMigrationLock = jest.fn(async () => undefined);
    const releaseMigrationLock = jest.fn(async () => undefined);
    const validateMigrationHistory = jest.fn(async () => [
      { id: undefined, name: migrationA, batch: 1 },
      { id: undefined, name: migrationB, batch: 1 },
    ]);
    const getAutoGeneratedCreateTableName = jest.fn(() => null);
    const doesMigrationTableExist = jest.fn(async () => true);
    const deleteAppliedMigration = jest.fn(async () => undefined);
    const loadModule = jest.fn(() => ({
      down: async (runner: { query(sql: string): Promise<void> }) => {
        await runner.query("SELECT 1;");
      },
    }));
    const appendAuditEvent = jest.fn();

    jest.doMock("chalk", () => passthroughChalk);
    jest.doMock("../cli/utils/PathMap", () => ({
      PathMap: {
        migrations: () => migrationsDir,
      },
    }));
    jest.doMock("../config/database", () => ({
      dbConfig: {
        connections: {},
      },
    }));
    jest.doMock("../core/connection/ConnectionFactory", () => ({
      getAdapter,
      closeAllConnections,
    }));
    jest.doMock("../core/connection/resolveConnectionName", () => ({
      resolveConnectionName,
    }));
    jest.doMock("../cli/utils/migrations/MigrationTracker", () => ({
      acquireMigrationLock,
      doesMigrationTableExist,
      deleteAppliedMigration,
      ensureMigrationTables,
      getAutoGeneratedCreateTableName,
      releaseMigrationLock,
      validateMigrationHistory,
    }));
    jest.doMock("../cli/utils/typescript/tsRuntime", () => ({
      loadModule,
    }));
    jest.doMock("../cli/utils/AuditTrail", () => ({
      appendAuditEvent,
    }));

    const { migrateRollback } = await import("../cli/commands/migrateRollback");
    await migrateRollback();

    expect(resolveConnectionName).toHaveBeenCalledWith(undefined, { test: false });
    expect(getAdapter).toHaveBeenCalledWith("sqlite");
    expect(ensureMigrationTables).toHaveBeenCalledWith(db);
    expect(acquireMigrationLock).toHaveBeenCalled();
    expect(releaseMigrationLock).toHaveBeenCalled();
    expect(deleteAppliedMigration).toHaveBeenCalledTimes(2);
    expect(appendAuditEvent).toHaveBeenCalledWith(
      expect.objectContaining({
        command: "migrate:rollback",
        connectionName: "sqlite",
        test: false,
        result: "success",
        metadata: expect.objectContaining({
          step: 1,
          allMigrations: false,
        }),
      })
    );
    expect(process.exitCode).toBe(0);

    fs.rmSync(root, { recursive: true, force: true });
  });
});
