import fs from "fs";
import os from "os";
import path from "path";
import { createAdapter } from "../core/connection/DriverAdapter.js";
import type { ConnectionName } from "../core/connection/DatabaseConnection.js";

const passthroughChalk = {
  __esModule: true,
  default: {
    gray: (v: string) => v,
    yellow: (v: string) => v,
    cyan: (v: string) => v,
    green: (v: string) => v,
    greenBright: (v: string) => v,
    red: (v: string) => v,
  },
};

type RollbackRow = {
  id?: number;
  name: string;
  batch: number;
  checksum?: string;
};

type RollbackHarnessOptions = {
  connectionName?: ConnectionName;
  driver?: string;
  rows?: RollbackRow[];
  fallbackTable?: string | null;
  doesTableExist?: boolean;
  doesTableExistError?: Error;
  ensureTablesError?: Error;
  loadModuleImpl?: (modulePath: string) => unknown;
  createFiles?: string[];
};

async function setupRollbackHarness(options: RollbackHarnessOptions = {}) {
  jest.resetModules();

  const connectionName = (options.connectionName ?? "mysql") as ConnectionName;
  const driver = options.driver ?? "mysql";
  const rows = options.rows ?? [];
  const fallbackTable =
    options.fallbackTable === undefined ? "ghosts" : options.fallbackTable;

  const root = fs.mkdtempSync(path.join(os.tmpdir(), "eloquent-phase17-rollback-"));
  const migrationsDir = path.join(root, String(connectionName));
  fs.mkdirSync(migrationsDir, { recursive: true });

  for (const fileName of options.createFiles ?? []) {
    fs.writeFileSync(path.join(migrationsDir, fileName), "// migration fixture\n", "utf8");
  }

  const db = {
    execute: jest.fn(async () => undefined),
    wrapId: jest.fn((id: string) => `\`${id}\``),
  };

  const getAdapter = jest.fn(async () => db);
  const closeAllConnections = jest.fn(async () => undefined);
  const resolveConnectionName = jest.fn(
    () => connectionName
  ) as jest.MockedFunction<(name?: string, opts?: { test?: boolean }) => ConnectionName>;

  const ensureMigrationTables = jest.fn(async () => driver);
  if (options.ensureTablesError) {
    ensureMigrationTables.mockRejectedValue(options.ensureTablesError);
  }
  const acquireMigrationLock = jest.fn(async () => undefined);
  const releaseMigrationLock = jest.fn(async () => undefined);
  const validateMigrationHistory = jest.fn(async () => rows as never);
  const getAutoGeneratedCreateTableName = jest.fn(() => fallbackTable as never);
  const deleteAppliedMigration = jest.fn(async () => undefined);
  const doesMigrationTableExist = jest.fn(async () => options.doesTableExist ?? true);
  if (options.doesTableExistError) {
    doesMigrationTableExist.mockRejectedValue(options.doesTableExistError);
  }

  const loadModule = jest.fn((modulePath: string) =>
    options.loadModuleImpl ? options.loadModuleImpl(modulePath) : {}
  );
  const appendAuditEvent = jest.fn();

  jest.doMock("chalk", () => passthroughChalk);
  jest.doMock("../cli/utils/PathMap", () => ({
    PathMap: {
      migrations: () => migrationsDir,
    },
  }));
  jest.doMock("../config/database", () => ({
    dbConfig: {
      connections: {
        [connectionName]: {
          driver,
        },
      },
    },
  }));
  jest.doMock("../core/connection/ConnectionFactory", () => ({
    getAdapter,
    closeAllConnections,
  }));
  jest.doMock("../core/connection/resolveConnectionName", () => ({
    resolveConnectionName,
  }));
  jest.doMock("../cli/utils/typescript/tsRuntime", () => ({
    loadModule,
  }));
  jest.doMock("../cli/utils/AuditTrail", () => ({
    appendAuditEvent,
  }));
  jest.doMock("../cli/utils/migrations/MigrationTracker", () => ({
    acquireMigrationLock,
    deleteAppliedMigration,
    doesMigrationTableExist,
    ensureMigrationTables,
    getAutoGeneratedCreateTableName,
    releaseMigrationLock,
    validateMigrationHistory,
  }));

  const rollbackModule = await import("../cli/commands/migrateRollback.js");

  return {
    root,
    migrationsDir,
    connectionName,
    db,
    migrateRollback: rollbackModule.migrateRollback,
    mocks: {
      getAdapter,
      closeAllConnections,
      resolveConnectionName,
      ensureMigrationTables,
      acquireMigrationLock,
      releaseMigrationLock,
      validateMigrationHistory,
      getAutoGeneratedCreateTableName,
      deleteAppliedMigration,
      doesMigrationTableExist,
      loadModule,
      appendAuditEvent,
    },
  };
}

describe("Branch coverage 100% - phase 17 rollback + adapter edge branches", () => {
  afterEach(() => {
    jest.restoreAllMocks();
    jest.clearAllMocks();
    jest.resetModules();
    process.exitCode = 0;
  });

  test("covers DriverAdapter unsupported-driver guard for undefined and unknown drivers", () => {
    expect(() => createAdapter("not_configured" as never, {} as never)).toThrow(
      "Unsupported driver for adapter: undefined"
    );

    const { dbConfig } = require("../config/database") as typeof import("../config/database.js");
    (dbConfig.connections as Record<string, unknown>).legacy = {
      driver: "oracle",
    };
    try {
      expect(() => createAdapter("legacy" as never, {} as never)).toThrow(
        "Unsupported driver for adapter: oracle"
      );
    } finally {
      delete (dbConfig.connections as Record<string, unknown>).legacy;
    }
  });

  test("covers rollback branch when computed step yields no target batches", async () => {
    const migrationName = "202603090001_create_users_table.ts";
    const harness = await setupRollbackHarness({
      rows: [{ id: 1, name: migrationName, batch: 1 }],
    });

    const logSpy = jest.spyOn(console, "log").mockImplementation(() => undefined);

    await harness.migrateRollback({
      connectionNames: [harness.connectionName],
      step: "bogus" as unknown as number,
      auditCommand: "migrate:rollback:phase17",
    });

    expect(logSpy).toHaveBeenCalledWith(expect.stringContaining("Nothing to roll back."));
    expect(harness.mocks.deleteAppliedMigration).not.toHaveBeenCalled();
    expect(harness.mocks.appendAuditEvent).toHaveBeenCalledWith(
      expect.objectContaining({
        command: "migrate:rollback:phase17",
        result: "success",
      })
    );

    fs.rmSync(harness.root, { recursive: true, force: true });
  });

  test("covers fallback rollback branch when generated table is already absent", async () => {
    const missingMigration = "202603090002_create_ghosts_table.ts";
    const harness = await setupRollbackHarness({
      rows: [{ id: 2, name: missingMigration, batch: 1 }],
      fallbackTable: "ghosts",
      doesTableExist: false,
    });

    const logSpy = jest.spyOn(console, "log").mockImplementation(() => undefined);

    await harness.migrateRollback({
      connectionNames: [harness.connectionName],
      allMigrations: true,
    });

    expect(logSpy).toHaveBeenCalledWith(
      expect.stringContaining('Fallback rollback: table "ghosts" already absent')
    );
    expect(harness.db.execute).not.toHaveBeenCalled();
    expect(harness.mocks.deleteAppliedMigration).toHaveBeenCalledWith(
      harness.db as never,
      missingMigration
    );
    expect(process.exitCode).toBe(0);

    fs.rmSync(harness.root, { recursive: true, force: true });
  });

  test("covers fallback error and no-fallback missing-file branches", async () => {
    const missingMigration = "202603090003_create_broken_table.ts";
    const errorSpy = jest.spyOn(console, "error").mockImplementation(() => undefined);

    const fallbackErrorHarness = await setupRollbackHarness({
      rows: [{ id: 3, name: missingMigration, batch: 1 }],
      fallbackTable: "broken_table",
      doesTableExistError: new Error("lookup failed"),
    });

    await fallbackErrorHarness.migrateRollback({
      connectionNames: [fallbackErrorHarness.connectionName],
      allMigrations: true,
    });

    expect(errorSpy).toHaveBeenCalledWith(
      expect.stringContaining(`Fallback rollback failed for ${missingMigration}:`)
    );
    expect(process.exitCode).toBe(1);

    fs.rmSync(fallbackErrorHarness.root, { recursive: true, force: true });
    process.exitCode = 0;

    const missingFileHarness = await setupRollbackHarness({
      rows: [{ id: 4, name: missingMigration, batch: 1 }],
      fallbackTable: null,
    });

    await missingFileHarness.migrateRollback({
      connectionNames: [missingFileHarness.connectionName],
      allMigrations: true,
    });

    expect(errorSpy).toHaveBeenCalledWith(
      expect.stringContaining(`Missing file: ${missingMigration}`)
    );
    expect(process.exitCode).toBe(1);

    fs.rmSync(missingFileHarness.root, { recursive: true, force: true });
  });

  test("covers no-down migration module and outer rollback catch branch", async () => {
    const migrationWithoutDown = "202603090004_update_users_table.ts";

    const noDownHarness = await setupRollbackHarness({
      rows: [{ id: 5, name: migrationWithoutDown, batch: 1 }],
      createFiles: [migrationWithoutDown],
      loadModuleImpl: () => ({}),
    });

    const logSpy = jest.spyOn(console, "log").mockImplementation(() => undefined);
    const errorSpy = jest.spyOn(console, "error").mockImplementation(() => undefined);

    await noDownHarness.migrateRollback({
      connectionNames: [noDownHarness.connectionName],
      allMigrations: true,
    });

    expect(logSpy).toHaveBeenCalledWith(
      expect.stringContaining(`No down() method: ${migrationWithoutDown}`)
    );
    expect(noDownHarness.mocks.deleteAppliedMigration).not.toHaveBeenCalled();
    expect(process.exitCode).toBe(0);

    fs.rmSync(noDownHarness.root, { recursive: true, force: true });

    const catchHarness = await setupRollbackHarness({
      rows: [{ id: 6, name: "202603090005_create_fail_table.ts", batch: 1 }],
      ensureTablesError: new Error("tracker bootstrap failed"),
    });

    await catchHarness.migrateRollback({
      connectionNames: [catchHarness.connectionName],
      allMigrations: true,
    });

    expect(errorSpy).toHaveBeenCalledWith(
      expect.stringContaining("Unable to read or validate migrations table.")
    );
    expect(catchHarness.mocks.releaseMigrationLock).toHaveBeenCalledTimes(1);
    expect(process.exitCode).toBe(1);

    fs.rmSync(catchHarness.root, { recursive: true, force: true });
  });
});
