import fs from "fs";
import os from "os";
import path from "path";
import { CacheManager } from "../core/cache/CacheManager.js";
import { CacheRegistry } from "../core/cache/CacheRegistry.js";
import { QueryCacheMixin } from "../core/orm/mixins/QueryCacheMixin.js";
import { HookStore } from "../core/orm/mixins/utils/HookStore.js";
import { ModelRegistry } from "../core/orm/mixins/utils/ModelRegistry.js";

const passthroughChalk = {
  __esModule: true,
  default: {
    gray: (v: string) => v,
    yellow: (v: string) => v,
    cyan: (v: string) => v,
    green: (v: string) => v,
    greenBright: (v: string) => v,
    red: (v: string) => v,
  },
};

abstract class EmptyBase {}

class Phase19CacheModel extends QueryCacheMixin(
  EmptyBase as unknown as abstract new (...args: any[]) => object
) {
  enable(ttl = 60): this {
    return (this as any).cache(ttl);
  }

  disable(): this {
    return (this as any).withoutCache();
  }

  runCached<T>(payload: unknown, execute: () => Promise<T>, group = "default"): Promise<T> {
    return (this as any).runWithCache(payload, execute, group);
  }
}

type RollbackRow = { id?: number; name: string; batch: number };

async function setupPgRollbackHarness(rows: RollbackRow[]) {
  jest.resetModules();

  const connectionName = "pg" as any;
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "eloquent-phase19-rollback-"));
  const migrationsDir = path.join(root, "pg");
  fs.mkdirSync(migrationsDir, { recursive: true });

  const db = {
    execute: jest.fn(async () => undefined),
    wrapId: jest.fn((id: string) => `"${id}"`),
  };

  const getAdapter = jest.fn(async () => db);
  const closeAllConnections = jest.fn(async () => undefined);
  const resolveConnectionName = jest.fn(() => "pg" as any);
  const ensureMigrationTables = jest.fn(async () => "pg");
  const acquireMigrationLock = jest.fn(async () => undefined);
  const releaseMigrationLock = jest.fn(async () => undefined);
  const validateMigrationHistory = jest.fn(async () => rows as never);
  const doesMigrationTableExist = jest.fn(async () => true);
  const deleteAppliedMigration = jest.fn(async () => undefined);
  const getAutoGeneratedCreateTableName = jest.fn((migrationFile: string) => {
    const match = /^.+_create_(.+)_table\.ts$/i.exec(migrationFile);
    return match ? match[1] : null;
  });
  const loadModule = jest.fn(() => ({}));
  const appendAuditEvent = jest.fn();

  jest.doMock("chalk", () => passthroughChalk);
  jest.doMock("../cli/utils/PathMap", () => ({
    PathMap: {
      migrations: () => migrationsDir,
    },
  }));
  jest.doMock("../config/database", () => ({
    dbConfig: {
      connections: {
        pg: {
          driver: "pg",
        },
      },
    },
  }));
  jest.doMock("../core/connection/ConnectionFactory", () => ({
    getAdapter,
    closeAllConnections,
  }));
  jest.doMock("../core/connection/resolveConnectionName", () => ({
    resolveConnectionName,
  }));
  jest.doMock("../cli/utils/migrations/MigrationTracker", () => ({
    acquireMigrationLock,
    doesMigrationTableExist,
    deleteAppliedMigration,
    ensureMigrationTables,
    getAutoGeneratedCreateTableName,
    releaseMigrationLock,
    validateMigrationHistory,
  }));
  jest.doMock("../cli/utils/typescript/tsRuntime", () => ({
    loadModule,
  }));
  jest.doMock("../cli/utils/AuditTrail", () => ({
    appendAuditEvent,
  }));

  const rollbackModule = await import("../cli/commands/migrateRollback.js");
  return {
    root,
    migrateRollback: rollbackModule.migrateRollback,
    db,
    mocks: {
      getAdapter,
      closeAllConnections,
      resolveConnectionName,
      ensureMigrationTables,
      acquireMigrationLock,
      releaseMigrationLock,
      validateMigrationHistory,
      doesMigrationTableExist,
      deleteAppliedMigration,
      getAutoGeneratedCreateTableName,
      loadModule,
      appendAuditEvent,
    },
  };
}

describe("Branch coverage 100% - phase 19 rollback/query-cache deep branches", () => {
  beforeEach(() => {
    jest.spyOn(console, "log").mockImplementation(() => undefined);
    jest.spyOn(console, "warn").mockImplementation(() => undefined);
    jest.spyOn(console, "error").mockImplementation(() => undefined);
  });

  afterEach(async () => {
    HookStore.clear();
    ModelRegistry.clear();
    await CacheRegistry.clearAll().catch(() => undefined);
    jest.restoreAllMocks();
    jest.resetModules();
    process.exitCode = 0;
  });

  test("covers QueryCache model-name fallback and hasModelDefaults branch permutations", async () => {
    Object.defineProperty(Phase19CacheModel, "name", { value: "", configurable: true });
    const model = new Phase19CacheModel();

    const clearModelSpy = jest.spyOn(CacheRegistry, "clearModel").mockResolvedValue(undefined);
    const clearGroupSpy = jest.spyOn(CacheRegistry, "clearGroup").mockResolvedValue(undefined);
    const cacheGetSpy = jest.spyOn(CacheManager, "get").mockResolvedValue(null);
    const cacheSetSpy = jest.spyOn(CacheManager, "set").mockResolvedValue(undefined);
    const addKeySpy = jest.spyOn(CacheRegistry, "addKey").mockImplementation(() => undefined);

    // Hook registration uses fallback model name "Model".
    const hooks = HookStore.snapshot(Phase19CacheModel as any);
    expect(hooks.created).toHaveLength(1);
    await hooks.created[0]({} as any);
    expect(clearModelSpy).toHaveBeenCalledWith("Model");
    await model.invalidateCacheGroup("groupA");
    expect(clearGroupSpy).toHaveBeenCalledWith("Model", "groupA");

    const executeSpy = jest.fn(async () => "value");
    const ctor = model.constructor as typeof Phase19CacheModel;

    // no defaults -> fast path
    delete ctor.defaultCacheTTL;
    delete ctor.cacheStrategy;
    delete ctor.cacheTTL;
    model.disable();
    await model.runCached({ page: 1 }, executeSpy, "g0");
    expect(cacheGetSpy).not.toHaveBeenCalled();

    // defaultCacheTTL only -> caching path
    ctor.defaultCacheTTL = 10;
    await model.runCached({ page: 2 }, executeSpy, "g1");
    expect(cacheGetSpy).toHaveBeenCalled();

    // cacheStrategy only -> caching path
    delete ctor.defaultCacheTTL;
    ctor.cacheStrategy = () => 7;
    await model.runCached({ page: 3 }, executeSpy, "g2");

    // cacheTTL empty -> fast path
    delete ctor.cacheStrategy;
    ctor.cacheTTL = {};
    cacheGetSpy.mockClear();
    await model.runCached({ page: 4 }, executeSpy, "g3");
    expect(cacheGetSpy).not.toHaveBeenCalled();

    // cacheTTL non-empty -> caching path and Model-prefixed key branch
    ctor.cacheTTL = { g4: 12 };
    model.enable(5);
    await model.runCached({ page: 5 }, executeSpy);
    expect(cacheSetSpy).toHaveBeenCalled();
    expect(addKeySpy).toHaveBeenCalled();
    expect(cacheGetSpy).toHaveBeenCalledWith(expect.stringMatching(/^Model:default:/));
  });

  test("covers migrateRollback pg-cascade fallback, sort/id-nullish path, and default connection resolution", async () => {
    const rows: RollbackRow[] = [
      { id: undefined, name: "20260309091001001_create_alphas_table.ts", batch: 2 },
      { id: 3, name: "20260309091001002_create_betas_table.ts", batch: 2 },
      { id: 1, name: "20260309091001003_create_gammas_table.ts", batch: 1 },
    ];
    const harness = await setupPgRollbackHarness(rows);

    await harness.migrateRollback({
      test: true,
      connectionNames: ["pg" as any],
      allMigrations: true,
    });

    expect(harness.db.execute).toHaveBeenCalledWith(
      expect.stringContaining("CASCADE"),
      []
    );
    const deletedNames = (harness.mocks.deleteAppliedMigration.mock.calls as Array<any[]>).map(
      (c) => c[1]
    );
    expect(deletedNames).toEqual([
      "20260309091001002_create_betas_table.ts",
      "20260309091001001_create_alphas_table.ts",
      "20260309091001003_create_gammas_table.ts",
    ]);
    expect(harness.mocks.appendAuditEvent).toHaveBeenCalledWith(
      expect.objectContaining({ test: true, result: "success" })
    );

    harness.mocks.deleteAppliedMigration.mockClear();
    harness.mocks.resolveConnectionName.mockClear();
    await harness.migrateRollback({ test: true, allMigrations: true });
    expect(harness.mocks.resolveConnectionName).toHaveBeenCalledWith(undefined, { test: true });

    fs.rmSync(harness.root, { recursive: true, force: true });
  });
});
