import fs from "fs";
import os from "os";
import path from "path";
import type { ConnectionName } from "../core/connection/DatabaseConnection";

const passthroughChalk = {
  __esModule: true,
  default: {
    gray: (value: string) => value,
    yellow: (value: string) => value,
    cyan: (value: string) => value,
    green: (value: string) => value,
    greenBright: (value: string) => value,
    red: (value: string) => value,
  },
};

type RollbackRow = {
  id?: string | number;
  name: string;
  batch: number;
  checksum?: string;
};

type MongoRollbackHarnessOptions = {
  connectionName?: ConnectionName;
  driver?: string;
  rows?: RollbackRow[];
  createFiles?: string[];
  existingCollections?: string[];
  fallbackCollection?: string | null;
  loadModuleImpl?: (modulePath: string) => unknown;
  ensureCollectionError?: Error;
  doesCollectionExistError?: Error;
  omitGetConnection?: boolean;
};

async function setupMongoRollbackHarness(
  options: MongoRollbackHarnessOptions = {},
) {
  jest.resetModules();

  const connectionName = (options.connectionName ?? "mongo") as ConnectionName;
  const driver = options.driver ?? "mongo";
  const rows = options.rows ?? [];
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "eloquent-lts5-rollback-"));
  const migrationsDir = path.join(root, String(connectionName));
  fs.mkdirSync(migrationsDir, { recursive: true });

  for (const fileName of options.createFiles ?? []) {
    fs.writeFileSync(path.join(migrationsDir, fileName), "// migration fixture\n", "utf8");
  }

  const existingCollections = new Set(options.existingCollections ?? []);
  const collections = new Map<
    string,
    {
      drop: jest.Mock<Promise<void>, []>;
      createIndex: jest.Mock<Promise<void>, [Record<string, 1 | -1>, Record<string, unknown>?]>;
      dropIndex: jest.Mock<Promise<void>, [string]>;
    }
  >();

  const getCollection = (name: string) => {
    const current = collections.get(name);
    if (current) {
      return current;
    }

    const created = {
      drop: jest.fn(async () => {
        existingCollections.delete(name);
      }),
      createIndex: jest.fn<
        Promise<void>,
        [Record<string, 1 | -1>, Record<string, unknown>?]
      >(async () => undefined),
      dropIndex: jest.fn<Promise<void>, [string]>(async () => undefined),
    };
    collections.set(name, created);
    return created;
  };

  const db = {
    listCollections: jest.fn((filter: { name?: string }) => ({
      toArray: async () =>
        filter?.name && existingCollections.has(filter.name) ? [{ name: filter.name }] : [],
    })),
    createCollection: jest.fn(async (name: string) => {
      existingCollections.add(name);
    }),
    collection: jest.fn((name: string) => getCollection(name)),
  };

  const getAdapter = jest.fn(async () => db);
  const getConnection = options.omitGetConnection ? undefined : jest.fn(async () => db);
  const closeAllConnections = jest.fn(async () => undefined);
  const resolveConnectionName = jest.fn(() => connectionName);

  const ensureMigrationTables = jest.fn(async () => driver);
  const acquireMigrationLock = jest.fn(async () => undefined);
  const deleteAppliedMigration = jest.fn(async () => undefined);
  const doesMigrationTableExist = jest.fn(async () => false);
  const getAutoGeneratedCreateTableName = jest.fn(() => options.fallbackCollection ?? null);
  const releaseMigrationLock = jest.fn(async () => undefined);
  const validateMigrationHistory = jest.fn(async () => rows);

  const ensureMigrationCollection = jest.fn(async () => undefined);
  if (options.ensureCollectionError) {
    ensureMigrationCollection.mockRejectedValue(options.ensureCollectionError);
  }
  const acquireMongoMigrationLock = jest.fn(async () => undefined);
  const deleteMongoAppliedMigration = jest.fn(async () => undefined);
  const doesCollectionExist = jest.fn(async (_db: unknown, name: string) =>
    existingCollections.has(name),
  );
  if (options.doesCollectionExistError) {
    doesCollectionExist.mockRejectedValue(options.doesCollectionExistError);
  }
  const readMongoAppliedMigrations = jest.fn(async () => rows);
  const releaseMongoMigrationLock = jest.fn(async () => undefined);
  const validateMongoMigrationHistory = jest.fn(async () => rows);

  const loadModule = jest.fn((modulePath: string) =>
    options.loadModuleImpl ? options.loadModuleImpl(modulePath) : {},
  );
  const appendAuditEvent = jest.fn();

  jest.doMock("chalk", () => passthroughChalk);
  jest.doMock("../cli/utils/PathMap", () => ({
    PathMap: {
      migrations: () => migrationsDir,
    },
  }));
  jest.doMock("../config/database", () => ({
    dbConfig: {
      connections: {
        [connectionName]: {
          driver,
        },
      },
    },
  }));
  jest.doMock("../core/connection/ConnectionFactory", () => ({
    getAdapter,
    ...(getConnection ? { getConnection } : {}),
    closeAllConnections,
  }));
  jest.doMock("../core/connection/resolveConnectionName", () => ({
    resolveConnectionName,
  }));
  jest.doMock("../cli/utils/migrations/MigrationTracker", () => ({
    acquireMigrationLock,
    deleteAppliedMigration,
    doesMigrationTableExist,
    ensureMigrationTables,
    getAutoGeneratedCreateTableName,
    releaseMigrationLock,
    validateMigrationHistory,
  }));
  jest.doMock("../cli/utils/migrations/MongoMigrationTracker", () => ({
    acquireMigrationLock: acquireMongoMigrationLock,
    deleteAppliedMigration: deleteMongoAppliedMigration,
    doesCollectionExist,
    ensureMigrationCollection,
    readAppliedMigrations: readMongoAppliedMigrations,
    releaseMigrationLock: releaseMongoMigrationLock,
    validateMigrationHistory: validateMongoMigrationHistory,
  }));
  jest.doMock("../cli/utils/typescript/tsRuntime", () => ({
    loadModule,
  }));
  jest.doMock("../cli/utils/AuditTrail", () => ({
    appendAuditEvent,
  }));

  const rollbackModule = await import("../cli/commands/migrateRollback");

  return {
    root,
    connectionName,
    db,
    collections,
    existingCollections,
    migrateRollback: rollbackModule.migrateRollback,
    mocks: {
      getAdapter,
      getConnection,
      closeAllConnections,
      resolveConnectionName,
      ensureMigrationCollection,
      acquireMongoMigrationLock,
      releaseMongoMigrationLock,
      releaseMigrationLock,
      validateMongoMigrationHistory,
      deleteMongoAppliedMigration,
      doesCollectionExist,
      appendAuditEvent,
    },
  };
}

describe("LTS phase 5 migrateRollback coverage", () => {
  afterEach(() => {
    jest.restoreAllMocks();
    jest.clearAllMocks();
    jest.resetModules();
    process.exitCode = 0;
  });

  test("plan tracks the dedicated migrateRollback coverage slice", () => {
    const planPath = path.resolve(
      process.cwd(),
      "validation tasks/LTS-Phase5-MigrateRollback-Coverage-Plan.md",
    );
    const content = fs.readFileSync(planPath, "utf8");

    expect(content).toContain("# LTS Phase 5 MigrateRollback Coverage Plan");
    expect(content).toContain("Status: COMPLETED");
    expect(content).toContain("src/cli/commands/migrateRollback.ts");
    expect(content).toContain("src/lab_test/lts.phase5.migrate-rollback-coverage.logic.test.ts");
  });

  test("covers Mongo fallback rollback when a generated collection still exists", async () => {
    const missingMigration = "202603150001_create_geo_points.ts";
    const harness = await setupMongoRollbackHarness({
      rows: [{ id: "mongo-1", name: missingMigration, batch: 7 }],
      existingCollections: ["geo_points"],
      fallbackCollection: "geo_points",
    });
    const logSpy = jest.spyOn(console, "log").mockImplementation(() => undefined);

    await harness.migrateRollback({
      connectionNames: [harness.connectionName],
      allMigrations: true,
      auditCommand: "lts:migrate:rollback",
    });

    expect(harness.collections.get("geo_points")?.drop).toHaveBeenCalled();
    expect(logSpy).toHaveBeenCalledWith(
      expect.stringContaining('Fallback rollback: dropped collection "geo_points"'),
    );
    expect(harness.mocks.deleteMongoAppliedMigration).toHaveBeenCalledWith(
      harness.db as never,
      missingMigration,
    );
    expect(harness.mocks.releaseMongoMigrationLock).toHaveBeenCalledWith(
      harness.db as never,
      expect.any(String),
    );
    expect(harness.mocks.appendAuditEvent).toHaveBeenCalledWith(
      expect.objectContaining({
        command: "lts:migrate:rollback",
        connectionName: harness.connectionName,
        result: "success",
        metadata: expect.objectContaining({
          step: Number.MAX_SAFE_INTEGER,
          allMigrations: true,
        }),
      }),
    );
    expect(process.exitCode).toBe(0);

    fs.rmSync(harness.root, { recursive: true, force: true });
  });

  test("covers Mongo down(context) helpers and the query guard", async () => {
    const migrationFile = "202603150002_manage_media.ts";
    let queryError = "";
    let observedCollection: unknown;
    const harness = await setupMongoRollbackHarness({
      rows: [{ id: "mongo-2", name: migrationFile, batch: 1 }],
      createFiles: [migrationFile],
      existingCollections: ["ghosts"],
      loadModuleImpl: () => ({
        down: async (ctx: {
          ensureCollection: (name: string) => Promise<void>;
          createIndex: (
            collectionName: string,
            keys: Record<string, 1 | -1>,
            options?: Record<string, unknown>,
          ) => Promise<void>;
          dropIndex: (collectionName: string, indexName: string) => Promise<void>;
          collection: (name: string) => unknown;
          dropCollection: (name: string) => Promise<void>;
          query: (sql: string) => Promise<void>;
        }) => {
          await ctx.ensureCollection("media");
          await ctx.createIndex("media", { user_id: 1 }, { unique: true });
          await ctx.dropIndex("media", "user_id_1");
          observedCollection = ctx.collection("media");
          await ctx.dropCollection("ghosts");
          try {
            await ctx.query("DROP TABLE users");
          } catch (error) {
            queryError = (error as Error).message;
          }
        },
      }),
    });

    await harness.migrateRollback({
      connectionNames: [harness.connectionName],
      allMigrations: true,
    });

    expect(harness.db.createCollection).toHaveBeenCalledWith("media");
    expect(harness.collections.get("media")?.createIndex).toHaveBeenCalledWith(
      { user_id: 1 },
      { unique: true },
    );
    expect(harness.collections.get("media")?.dropIndex).toHaveBeenCalledWith("user_id_1");
    expect(observedCollection).toBe(harness.collections.get("media"));
    expect(queryError).toContain("Mongo migrations do not support SQL query() calls");
    expect(harness.collections.get("ghosts")?.drop).toHaveBeenCalled();
    expect(harness.mocks.deleteMongoAppliedMigration).toHaveBeenCalledWith(
      harness.db as never,
      migrationFile,
    );
    expect(process.exitCode).toBe(0);

    fs.rmSync(harness.root, { recursive: true, force: true });
  });

  test("falls back to getAdapter when getConnection is unavailable and records failure audit", async () => {
    const errorSpy = jest.spyOn(console, "error").mockImplementation(() => undefined);
    const harness = await setupMongoRollbackHarness({
      omitGetConnection: true,
      ensureCollectionError: new Error("mongo bootstrap failed"),
    });

    await harness.migrateRollback({
      test: true,
      step: 0,
      auditCommand: "lts:migrate:rollback",
    });

    expect(harness.mocks.resolveConnectionName).toHaveBeenCalledWith(undefined, {
      test: true,
    });
    expect(harness.mocks.getAdapter).toHaveBeenCalledWith(harness.connectionName);
    expect(errorSpy).toHaveBeenCalledWith(
      expect.stringContaining("Unable to read or validate migrations collection."),
    );
    expect(harness.mocks.releaseMongoMigrationLock).toHaveBeenCalledWith(
      harness.db as never,
      expect.any(String),
    );
    expect(harness.mocks.closeAllConnections).toHaveBeenCalled();
    expect(harness.mocks.appendAuditEvent).toHaveBeenCalledWith(
      expect.objectContaining({
        command: "lts:migrate:rollback",
        connectionName: harness.connectionName,
        test: true,
        result: "failure",
        metadata: expect.objectContaining({
          step: 1,
          allMigrations: false,
        }),
      }),
    );
    expect(process.exitCode).toBe(1);

    fs.rmSync(harness.root, { recursive: true, force: true });
  });

  test("covers unsupported-driver skip with normalized default step and default audit command", async () => {
    const warnSpy = jest.spyOn(console, "warn").mockImplementation(() => undefined);
    const harness = await setupMongoRollbackHarness({
      connectionName: "legacy" as ConnectionName,
      driver: "oracle",
    });

    await harness.migrateRollback({
      step: 0,
    });

    expect(harness.mocks.resolveConnectionName).toHaveBeenCalledWith(undefined, {
      test: false,
    });
    expect(harness.mocks.getAdapter).not.toHaveBeenCalled();
    expect(warnSpy).toHaveBeenCalledWith(
      expect.stringContaining('Rollback skipped: "legacy" has unsupported driver "oracle".'),
    );
    expect(harness.mocks.appendAuditEvent).toHaveBeenCalledWith(
      expect.objectContaining({
        command: "migrate:rollback",
        connectionName: "legacy",
        result: "success",
        metadata: expect.objectContaining({
          step: 1,
          allMigrations: false,
        }),
      }),
    );
    expect(process.exitCode).toBe(0);

    fs.rmSync(harness.root, { recursive: true, force: true });
  });

  test("covers missing migrations directory and SQL empty-history success", async () => {
    const missingDirHarness = await setupMongoRollbackHarness({
      connectionName: "missing" as ConnectionName,
      driver: "sqlite",
    });
    const logSpy = jest.spyOn(console, "log").mockImplementation(() => undefined);

    fs.rmSync(path.join(missingDirHarness.root, String(missingDirHarness.connectionName)), {
      recursive: true,
      force: true,
    });

    await missingDirHarness.migrateRollback({
      connectionNames: [missingDirHarness.connectionName],
    });

    expect(logSpy).toHaveBeenCalledWith(
      expect.stringContaining(
        `No migrations directory found for ${String(missingDirHarness.connectionName)}.`,
      ),
    );
    expect(missingDirHarness.mocks.appendAuditEvent).toHaveBeenCalledWith(
      expect.objectContaining({
        result: "success",
      }),
    );
    expect(process.exitCode).toBe(0);

    fs.rmSync(missingDirHarness.root, { recursive: true, force: true });
    process.exitCode = 0;

    const sqlEmptyHarness = await setupMongoRollbackHarness({
      connectionName: "sqlite" as ConnectionName,
      driver: "sqlite",
      rows: [],
    });

    await sqlEmptyHarness.migrateRollback({
      connectionNames: [sqlEmptyHarness.connectionName],
    });

    expect(logSpy).toHaveBeenCalledWith(
      expect.stringContaining("No migrations found to roll back."),
    );
    expect(sqlEmptyHarness.mocks.appendAuditEvent).toHaveBeenCalledWith(
      expect.objectContaining({
        connectionName: sqlEmptyHarness.connectionName,
        result: "success",
      }),
    );
    expect(process.exitCode).toBe(0);

    fs.rmSync(sqlEmptyHarness.root, { recursive: true, force: true });
  });

  test("covers Mongo empty-history and bogus-step no-target branches", async () => {
    const logSpy = jest.spyOn(console, "log").mockImplementation(() => undefined);

    const emptyHarness = await setupMongoRollbackHarness({
      rows: [],
    });

    await emptyHarness.migrateRollback({
      connectionNames: [emptyHarness.connectionName],
    });

    expect(logSpy).toHaveBeenCalledWith(
      expect.stringContaining("No migrations found to roll back."),
    );
    expect(process.exitCode).toBe(0);

    fs.rmSync(emptyHarness.root, { recursive: true, force: true });
    process.exitCode = 0;

    const noTargetHarness = await setupMongoRollbackHarness({
      rows: [
        { id: "2", name: "202603150010_second.ts", batch: 1 },
        { id: "1", name: "202603150009_first.ts", batch: 1 },
      ],
    });

    await noTargetHarness.migrateRollback({
      connectionNames: [noTargetHarness.connectionName],
      step: "bogus" as unknown as number,
    });

    expect(logSpy).toHaveBeenCalledWith(expect.stringContaining("Nothing to roll back."));
    expect(noTargetHarness.mocks.deleteMongoAppliedMigration).not.toHaveBeenCalled();
    expect(process.exitCode).toBe(0);

    fs.rmSync(noTargetHarness.root, { recursive: true, force: true });
  });

  test("covers Mongo already-absent fallback, fallback error, and no-fallback missing file branches", async () => {
    const logSpy = jest.spyOn(console, "log").mockImplementation(() => undefined);
    const errorSpy = jest.spyOn(console, "error").mockImplementation(() => undefined);

    const absentHarness = await setupMongoRollbackHarness({
      rows: [{ id: "mongo-3", name: "202603150003_missing.ts", batch: 1 }],
      fallbackCollection: "ghosts",
    });

    await absentHarness.migrateRollback({
      connectionNames: [absentHarness.connectionName],
      allMigrations: true,
    });

    expect(logSpy).toHaveBeenCalledWith(
      expect.stringContaining('Fallback rollback: collection "ghosts" already absent'),
    );
    expect(absentHarness.mocks.deleteMongoAppliedMigration).toHaveBeenCalled();
    expect(process.exitCode).toBe(0);

    fs.rmSync(absentHarness.root, { recursive: true, force: true });
    process.exitCode = 0;

    const fallbackErrorHarness = await setupMongoRollbackHarness({
      rows: [{ id: "mongo-4", name: "202603150004_broken.ts", batch: 1 }],
      fallbackCollection: "broken_collection",
      doesCollectionExistError: new Error("lookup failed"),
    });

    await fallbackErrorHarness.migrateRollback({
      connectionNames: [fallbackErrorHarness.connectionName],
      allMigrations: true,
    });

    expect(errorSpy).toHaveBeenCalledWith(
      expect.stringContaining("Fallback rollback failed for 202603150004_broken.ts:"),
    );
    expect(process.exitCode).toBe(1);

    fs.rmSync(fallbackErrorHarness.root, { recursive: true, force: true });
    process.exitCode = 0;

    const missingFileHarness = await setupMongoRollbackHarness({
      rows: [{ id: "mongo-5", name: "202603150005_missing.ts", batch: 1 }],
      fallbackCollection: null,
    });

    await missingFileHarness.migrateRollback({
      connectionNames: [missingFileHarness.connectionName],
      allMigrations: true,
    });

    expect(errorSpy).toHaveBeenCalledWith(
      expect.stringContaining("Missing file: 202603150005_missing.ts"),
    );
    expect(process.exitCode).toBe(1);

    fs.rmSync(missingFileHarness.root, { recursive: true, force: true });
  });

  test("covers Mongo no-down and down-error branches for existing migration files", async () => {
    const logSpy = jest.spyOn(console, "log").mockImplementation(() => undefined);
    const errorSpy = jest.spyOn(console, "error").mockImplementation(() => undefined);

    const noDownHarness = await setupMongoRollbackHarness({
      rows: [{ id: "mongo-6", name: "202603150006_nodown.ts", batch: 1 }],
      createFiles: ["202603150006_nodown.ts"],
      loadModuleImpl: () => ({}),
    });

    await noDownHarness.migrateRollback({
      connectionNames: [noDownHarness.connectionName],
      allMigrations: true,
    });

    expect(logSpy).toHaveBeenCalledWith(
      expect.stringContaining("No down() method: 202603150006_nodown.ts"),
    );
    expect(process.exitCode).toBe(0);

    fs.rmSync(noDownHarness.root, { recursive: true, force: true });
    process.exitCode = 0;

    const downErrorHarness = await setupMongoRollbackHarness({
      rows: [{ id: "mongo-7", name: "202603150007_fail.ts", batch: 1 }],
      createFiles: ["202603150007_fail.ts"],
      loadModuleImpl: () => ({
        down: async () => {
          throw new Error("mongo down failed");
        },
      }),
    });

    await downErrorHarness.migrateRollback({
      connectionNames: [downErrorHarness.connectionName],
      allMigrations: true,
    });

    expect(errorSpy).toHaveBeenCalledWith(
      expect.stringContaining("Error rolling back 202603150007_fail.ts:"),
    );
    expect(process.exitCode).toBe(1);

    fs.rmSync(downErrorHarness.root, { recursive: true, force: true });
  });

  test("covers Mongo context no-op branches plus batch and id fallback sorting", async () => {
    const migrationFiles = [
      "202603150010_manage_media_a.ts",
      "202603150011_manage_media_b.ts",
      "202603150012_manage_media_c.ts",
    ];
    const harness = await setupMongoRollbackHarness({
      rows: [
        { name: migrationFiles[0], batch: 2 },
        { name: migrationFiles[1], batch: 2 },
        { name: migrationFiles[2], batch: 1 },
      ],
      createFiles: migrationFiles,
      existingCollections: ["media"],
      loadModuleImpl: (modulePath: string) => ({
        down: async (ctx: {
          ensureCollection: (name: string) => Promise<void>;
          dropCollection: (name: string) => Promise<void>;
          createIndex: (
            collectionName: string,
            keys: Record<string, 1 | -1>,
            options?: Record<string, unknown>,
          ) => Promise<void>;
          query: (sql: string) => Promise<void>;
        }) => {
          if (modulePath.endsWith(migrationFiles[0])) {
            await ctx.ensureCollection("media");
            await ctx.dropCollection("ghosts");
            await ctx.createIndex("media", { user_id: 1 });
            await ctx.query("   ");
          }
        },
      }),
    });

    await harness.migrateRollback({
      connectionNames: [harness.connectionName],
      allMigrations: true,
    });

    expect(harness.db.createCollection).not.toHaveBeenCalled();
    expect(harness.collections.get("ghosts")?.drop).toBeUndefined();
    expect(harness.collections.get("media")?.createIndex).toHaveBeenCalledWith(
      { user_id: 1 },
      {},
    );
    expect(process.exitCode).toBe(0);

    fs.rmSync(harness.root, { recursive: true, force: true });
  });

  test("releases Mongo and SQL locks on rollback failure after lock acquisition", async () => {
    const mongoHarness = await setupMongoRollbackHarness({
      rows: [{ id: "mongo-fail", name: "202603150013_fail.ts", batch: 1 }],
      createFiles: ["202603150013_fail.ts"],
      loadModuleImpl: () => ({
        down: async () => {
          throw new Error("mongo rollback failed");
        },
      }),
    });

    await mongoHarness.migrateRollback({
      connectionNames: [mongoHarness.connectionName],
      allMigrations: true,
    });

    expect(mongoHarness.mocks.acquireMongoMigrationLock).toHaveBeenCalled();
    expect(mongoHarness.mocks.releaseMongoMigrationLock).toHaveBeenCalledWith(
      mongoHarness.db as never,
      expect.any(String),
    );
    fs.rmSync(mongoHarness.root, { recursive: true, force: true });
    process.exitCode = 0;

    const sqlHarness = await setupMongoRollbackHarness({
      connectionName: "sqlite" as ConnectionName,
      driver: "sqlite",
      rows: [{ id: 1, name: "202603150014_fail.ts", batch: 1 }],
      createFiles: ["202603150014_fail.ts"],
      loadModuleImpl: () => ({
        down: async () => {
          throw new Error("sql rollback failed");
        },
      }),
    });

    await sqlHarness.migrateRollback({
      connectionNames: [sqlHarness.connectionName],
      allMigrations: true,
    });

    expect(sqlHarness.mocks.releaseMigrationLock).toHaveBeenCalledWith(
      sqlHarness.db as never,
      expect.any(String),
      expect.objectContaining({ success: false }),
    );
    fs.rmSync(sqlHarness.root, { recursive: true, force: true });
  });
});
