import fs from "fs";
import os from "os";
import path from "path";
import type { ConnectionName } from "../core/connection/DatabaseConnection.js";

const passthroughChalk = {
  __esModule: true,
  default: {
    gray: (value: string) => value,
    yellow: (value: string) => value,
    cyan: (value: string) => value,
    green: (value: string) => value,
    greenBright: (value: string) => value,
    red: (value: string) => value,
  },
};

type RollbackRow = {
  id?: string | number;
  name: string;
  batch: number;
};

type SqlRollbackHarnessOptions = {
  connectionName?: ConnectionName;
  driver?: string;
  rows?: RollbackRow[];
  createFiles?: string[];
  fallbackTable?: string | null;
  existingTables?: string[];
  loadModuleImpl?: (modulePath: string) => unknown;
  omitConnectionConfig?: boolean;
  createMigrationsDir?: boolean;
  validateHistoryError?: Error;
};

async function setupSqlRollbackHarness(options: SqlRollbackHarnessOptions = {}) {
  jest.resetModules();

  const connectionName = (options.connectionName ?? "sqlite") as ConnectionName;
  const driver = options.driver ?? "sqlite";
  const rows = options.rows ?? [];
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "eloquent-lts5-rollback-cont-"));
  const migrationsDir = path.join(root, String(connectionName));

  if (options.createMigrationsDir !== false) {
    fs.mkdirSync(migrationsDir, { recursive: true });
    for (const fileName of options.createFiles ?? []) {
      fs.writeFileSync(path.join(migrationsDir, fileName), "// migration fixture\n", "utf8");
    }
  }

  const existingTables = new Set(options.existingTables ?? []);
  const db = {
    execute: jest.fn<Promise<void>, [string, unknown[]?]>(async (sql: string) => {
      const match = /DROP TABLE IF EXISTS [`"]?([^`";\s]+)[`"]?(?: CASCADE)?;/i.exec(sql);
      if (match?.[1]) {
        existingTables.delete(match[1]);
      }
    }),
    wrapId: jest.fn((value: string) => `\`${value}\``),
  };

  const getAdapter = jest.fn(async () => db);
  const closeAllConnections = jest.fn(async () => undefined);
  const resolveConnectionName = jest.fn(() => connectionName);
  const ensureMigrationTables = jest.fn(async () => driver);
  const acquireMigrationLock = jest.fn(async () => undefined);
  const deleteAppliedMigration = jest.fn(async () => undefined);
  const doesMigrationTableExist = jest.fn(async (_db: unknown, tableName: string) =>
    existingTables.has(tableName),
  );
  const getAutoGeneratedCreateTableName = jest.fn(() => options.fallbackTable ?? null);
  const releaseMigrationLock = jest.fn(async () => undefined);
  const validateMigrationHistory = jest.fn(async () => rows);
  if (options.validateHistoryError) {
    validateMigrationHistory.mockRejectedValue(options.validateHistoryError);
  }

  const loadModule = jest.fn((modulePath: string) =>
    options.loadModuleImpl ? options.loadModuleImpl(modulePath) : {},
  );
  const appendAuditEvent = jest.fn();

  jest.doMock("chalk", () => passthroughChalk);
  jest.doMock("../cli/utils/PathMap", () => ({
    PathMap: {
      migrations: () => migrationsDir,
    },
  }));
  jest.doMock("../config/database", () => ({
    dbConfig: {
      connections: options.omitConnectionConfig
        ? {}
        : {
            [connectionName]: {
              driver,
            },
          },
    },
  }));
  jest.doMock("../core/connection/ConnectionFactory", () => ({
    getAdapter,
    getConnection: jest.fn(async () => db),
    closeAllConnections,
  }));
  jest.doMock("../core/connection/resolveConnectionName", () => ({
    resolveConnectionName,
  }));
  jest.doMock("../cli/utils/migrations/MigrationTracker", () => ({
    acquireMigrationLock,
    doesMigrationTableExist,
    deleteAppliedMigration,
    ensureMigrationTables,
    getAutoGeneratedCreateTableName,
    releaseMigrationLock,
    validateMigrationHistory,
  }));
  jest.doMock("../cli/utils/migrations/MongoMigrationTracker", () => ({
    acquireMigrationLock: jest.fn(async () => undefined),
    deleteAppliedMigration: jest.fn(async () => undefined),
    doesCollectionExist: jest.fn(async () => false),
    ensureMigrationCollection: jest.fn(async () => undefined),
    readAppliedMigrations: jest.fn(async () => []),
    releaseMigrationLock: jest.fn(async () => undefined),
    validateMigrationHistory: jest.fn(async () => []),
  }));
  jest.doMock("../cli/utils/typescript/tsRuntime", () => ({
    loadModule,
  }));
  jest.doMock("../cli/utils/AuditTrail", () => ({
    appendAuditEvent,
  }));

  const rollbackModule = await import("../cli/commands/migrateRollback.js");

  return {
    root,
    connectionName,
    db,
    migrateRollback: rollbackModule.migrateRollback,
    mocks: {
      getAdapter,
      closeAllConnections,
      resolveConnectionName,
      ensureMigrationTables,
      acquireMigrationLock,
      deleteAppliedMigration,
      doesMigrationTableExist,
      getAutoGeneratedCreateTableName,
      releaseMigrationLock,
      validateMigrationHistory,
      loadModule,
      appendAuditEvent,
    },
  };
}

describe("LTS phase 5 migrateRollback continuation", () => {
  afterEach(() => {
    jest.restoreAllMocks();
    jest.clearAllMocks();
    jest.resetModules();
    process.exitCode = 0;
  });

  test("continuation plan records the completed SQL-side rollback slice", () => {
    const planPath = path.resolve(
      process.cwd(),
      "validation tasks/LTS-Phase5-MigrateRollback-Continuation-Plan.md",
    );
    const content = fs.readFileSync(planPath, "utf8");

    expect(content).toContain("# LTS Phase 5 MigrateRollback Continuation Plan");
    expect(content).toContain("Status: COMPLETED");
    expect(content).toContain("line `121`");
    expect(content).toContain("line `360`");
    expect(content).toContain(
      "src/lab_test/lts.phase5.migrate-rollback-continuation.logic.test.ts",
    );
    expect(content).toContain("focused Docker `v8` run:");
    expect(content).toContain(
      "`migrateRollback.ts` -> `100%` statements / `100%` branches / `100%` functions / `100%` lines",
    );
  });

  test("covers SQL no-target rollback and driver fallback resolution when config is absent", async () => {
    const logSpy = jest.spyOn(console, "log").mockImplementation(() => undefined);
    const harness = await setupSqlRollbackHarness({
      connectionName: "sqlite" as ConnectionName,
      rows: [
        { id: 1, name: "202603220001_first.ts", batch: 1 },
        { id: 2, name: "202603220002_second.ts", batch: 1 },
      ],
      omitConnectionConfig: true,
    });

    await harness.migrateRollback({
      connectionNames: [harness.connectionName],
      step: "bogus" as unknown as number,
    });

    expect(harness.mocks.getAdapter).toHaveBeenCalledWith(harness.connectionName);
    expect(logSpy).toHaveBeenCalledWith(expect.stringContaining("Nothing to roll back."));
    expect(harness.mocks.deleteAppliedMigration).not.toHaveBeenCalled();
    expect(process.exitCode).toBe(0);

    fs.rmSync(harness.root, { recursive: true, force: true });
  });

  test("covers SQL sort comparator batch and nullish id branches", async () => {
    const logSpy = jest.spyOn(console, "log").mockImplementation(() => undefined);
    const harness = await setupSqlRollbackHarness({
      rows: [
        { name: "202603220010_fourth.ts", batch: 2 },
        { id: 5, name: "202603220011_second.ts", batch: 1 },
        { name: "202603220012_first.ts", batch: 1 },
      ],
      createFiles: [
        "202603220010_fourth.ts",
        "202603220011_second.ts",
        "202603220012_first.ts",
      ],
      createMigrationsDir: true,
    });

    await harness.migrateRollback({
      connectionNames: [harness.connectionName],
      allMigrations: true,
    });

    expect(logSpy).toHaveBeenCalledWith(
      expect.stringContaining("No down() method: 202603220010_fourth.ts"),
    );
    expect(logSpy).toHaveBeenCalledWith(
      expect.stringContaining("No down() method: 202603220011_second.ts"),
    );
    expect(logSpy).toHaveBeenCalledWith(
      expect.stringContaining("No down() method: 202603220012_first.ts"),
    );
    expect(process.exitCode).toBe(0);

    fs.rmSync(harness.root, { recursive: true, force: true });
  });

  test("covers SQL fallback rollback branches for dropped, absent, failed, and missing-file cases", async () => {
    const logSpy = jest.spyOn(console, "log").mockImplementation(() => undefined);
    const errorSpy = jest.spyOn(console, "error").mockImplementation(() => undefined);

    const droppedHarness = await setupSqlRollbackHarness({
      connectionName: "pg" as ConnectionName,
      driver: "pg",
      rows: [{ id: 1, name: "202603220003_missing.ts", batch: 2 }],
      fallbackTable: "users",
      existingTables: ["users"],
    });
    await droppedHarness.migrateRollback({
      connectionNames: [droppedHarness.connectionName],
      allMigrations: true,
    });
    expect(droppedHarness.db.execute).toHaveBeenCalledWith(
      "DROP TABLE IF EXISTS `users` CASCADE;",
      [],
    );
    expect(logSpy).toHaveBeenCalledWith(
      expect.stringContaining('Fallback rollback: dropped table "users"'),
    );
    expect(droppedHarness.mocks.deleteAppliedMigration).toHaveBeenCalled();
    fs.rmSync(droppedHarness.root, { recursive: true, force: true });
    process.exitCode = 0;

    const sqliteDroppedHarness = await setupSqlRollbackHarness({
      connectionName: "sqlite" as ConnectionName,
      driver: "sqlite",
      rows: [{ id: 1, name: "202603220003b_missing.ts", batch: 2 }],
      fallbackTable: "profiles",
      existingTables: ["profiles"],
    });
    await sqliteDroppedHarness.migrateRollback({
      connectionNames: [sqliteDroppedHarness.connectionName],
      allMigrations: true,
    });
    expect(sqliteDroppedHarness.db.execute).toHaveBeenCalledWith(
      "DROP TABLE IF EXISTS `profiles`;",
      [],
    );
    fs.rmSync(sqliteDroppedHarness.root, { recursive: true, force: true });
    process.exitCode = 0;

    const absentHarness = await setupSqlRollbackHarness({
      connectionName: "pg" as ConnectionName,
      driver: "pg",
      rows: [{ id: 1, name: "202603220004_missing.ts", batch: 2 }],
      fallbackTable: "posts",
      existingTables: [],
    });
    await absentHarness.migrateRollback({
      connectionNames: [absentHarness.connectionName],
      allMigrations: true,
    });
    expect(logSpy).toHaveBeenCalledWith(
      expect.stringContaining('Fallback rollback: table "posts" already absent'),
    );
    expect(absentHarness.db.execute).not.toHaveBeenCalledWith(
      expect.stringContaining("DROP TABLE IF EXISTS `posts` CASCADE;"),
      expect.anything(),
    );
    fs.rmSync(absentHarness.root, { recursive: true, force: true });
    process.exitCode = 0;

    const fallbackErrorHarness = await setupSqlRollbackHarness({
      rows: [{ id: 1, name: "202603220005_missing.ts", batch: 2 }],
      fallbackTable: "comments",
      existingTables: ["comments"],
    });
    fallbackErrorHarness.mocks.doesMigrationTableExist.mockRejectedValueOnce(new Error("lookup failed"));
    await fallbackErrorHarness.migrateRollback({
      connectionNames: [fallbackErrorHarness.connectionName],
      allMigrations: true,
    });
    expect(errorSpy).toHaveBeenCalledWith(
      expect.stringContaining("Fallback rollback failed for 202603220005_missing.ts:"),
    );
    expect(process.exitCode).toBe(1);
    fs.rmSync(fallbackErrorHarness.root, { recursive: true, force: true });
    process.exitCode = 0;

    const missingHarness = await setupSqlRollbackHarness({
      rows: [{ id: 1, name: "202603220006_missing.ts", batch: 2 }],
      fallbackTable: null,
    });
    await missingHarness.migrateRollback({
      connectionNames: [missingHarness.connectionName],
      allMigrations: true,
    });
    expect(errorSpy).toHaveBeenCalledWith(
      expect.stringContaining("Missing file: 202603220006_missing.ts"),
    );
    expect(process.exitCode).toBe(1);
    fs.rmSync(missingHarness.root, { recursive: true, force: true });
  });

  test("covers SQL no-down branch, successful down branch, and outer validation failure", async () => {
    const logSpy = jest.spyOn(console, "log").mockImplementation(() => undefined);
    const errorSpy = jest.spyOn(console, "error").mockImplementation(() => undefined);

    const noDownHarness = await setupSqlRollbackHarness({
      rows: [{ id: 1, name: "202603220007_nodown.ts", batch: 1 }],
      createFiles: ["202603220007_nodown.ts"],
      loadModuleImpl: () => ({}),
    });
    await noDownHarness.migrateRollback({
      connectionNames: [noDownHarness.connectionName],
      allMigrations: true,
    });
    expect(logSpy).toHaveBeenCalledWith(
      expect.stringContaining("No down() method: 202603220007_nodown.ts"),
    );
    fs.rmSync(noDownHarness.root, { recursive: true, force: true });
    process.exitCode = 0;

    const successHarness = await setupSqlRollbackHarness({
      connectionName: "pg" as ConnectionName,
      driver: "pg",
      rows: [{ id: 4, name: "202603220008_success.ts", batch: 1 }],
      createFiles: ["202603220008_success.ts"],
      loadModuleImpl: () => ({
        down: async (ctx: { query: (sql: string, params?: unknown[]) => Promise<void> }) => {
          await ctx.query("DROP TABLE IF EXISTS users CASCADE;");
        },
      }),
    });
    await successHarness.migrateRollback({
      connectionNames: [successHarness.connectionName],
      allMigrations: true,
      auditCommand: "lts:migrate:rollback",
    });
    expect(successHarness.db.execute).toHaveBeenCalledWith(
      "DROP TABLE IF EXISTS users CASCADE;",
      [],
    );
    expect(successHarness.mocks.deleteAppliedMigration).toHaveBeenCalledWith(
      successHarness.db as never,
      "202603220008_success.ts",
    );
    expect(logSpy).toHaveBeenCalledWith(
      expect.stringContaining("Rolled back: 202603220008_success.ts"),
    );
    expect(successHarness.mocks.releaseMigrationLock).toHaveBeenCalledWith(
      successHarness.db as never,
      expect.any(String),
      expect.objectContaining({ success: true }),
    );
    expect(successHarness.mocks.appendAuditEvent).toHaveBeenCalledWith(
      expect.objectContaining({
        command: "lts:migrate:rollback",
        result: "success",
      }),
    );
    fs.rmSync(successHarness.root, { recursive: true, force: true });
    process.exitCode = 0;

    const outerErrorHarness = await setupSqlRollbackHarness({
      rows: [{ id: 1, name: "202603220009_fail.ts", batch: 1 }],
      validateHistoryError: new Error("sql history failed"),
    });
    await outerErrorHarness.migrateRollback({
      connectionNames: [outerErrorHarness.connectionName],
      allMigrations: true,
    });
    expect(errorSpy).toHaveBeenCalledWith(
      expect.stringContaining("Unable to read or validate migrations table."),
    );
    expect(outerErrorHarness.mocks.releaseMigrationLock).toHaveBeenCalledWith(
      outerErrorHarness.db as never,
      expect.any(String),
      expect.objectContaining({ success: false }),
    );
    expect(process.exitCode).toBe(1);
    fs.rmSync(outerErrorHarness.root, { recursive: true, force: true });
  });
});
