import fs from "fs";
import path from "path";
import { PathMap } from "../cli/utils/PathMap";
import { migrateRollback } from "../cli/commands/migrateRollback";
import { loadModule } from "../cli/utils/typescript/tsRuntime";
import {
  closeAllConnections,
  getAdapter,
} from "../core/connection/ConnectionFactory";
import { resolveConnectionName } from "../core/connection/resolveConnectionName";
import {
  acquireMigrationLock,
  deleteAppliedMigration,
  doesMigrationTableExist,
  ensureMigrationTables,
  getAutoGeneratedCreateTableName,
  releaseMigrationLock,
  validateMigrationHistory,
} from "../cli/utils/migrations/MigrationTracker";

jest.mock("chalk", () => ({
  __esModule: true,
  default: {
    gray: (value: string) => value,
    yellow: (value: string) => value,
    cyan: (value: string) => value,
    green: (value: string) => value,
    greenBright: (value: string) => value,
    red: (value: string) => value,
  },
}));

jest.mock("../core/connection/ConnectionFactory", () => ({
  getAdapter: jest.fn(),
  closeAllConnections: jest.fn(),
}));

jest.mock("../core/connection/resolveConnectionName", () => ({
  resolveConnectionName: jest.fn(),
}));

jest.mock("../cli/utils/typescript/tsRuntime", () => ({
  loadModule: jest.fn(),
}));

jest.mock("../cli/utils/migrations/MigrationTracker", () => ({
  acquireMigrationLock: jest.fn(),
  deleteAppliedMigration: jest.fn(),
  doesMigrationTableExist: jest.fn(),
  ensureMigrationTables: jest.fn(),
  getAutoGeneratedCreateTableName: jest.fn(),
  releaseMigrationLock: jest.fn(),
  validateMigrationHistory: jest.fn(),
}));

const mockedGetAdapter = getAdapter as jest.MockedFunction<typeof getAdapter>;
const mockedCloseAllConnections =
  closeAllConnections as jest.MockedFunction<typeof closeAllConnections>;
const mockedResolveConnectionName =
  resolveConnectionName as jest.MockedFunction<typeof resolveConnectionName>;
const mockedLoadModule = loadModule as jest.MockedFunction<typeof loadModule>;
const mockedAcquireMigrationLock =
  acquireMigrationLock as jest.MockedFunction<typeof acquireMigrationLock>;
const mockedDeleteAppliedMigration =
  deleteAppliedMigration as jest.MockedFunction<typeof deleteAppliedMigration>;
const mockedDoesMigrationTableExist =
  doesMigrationTableExist as jest.MockedFunction<typeof doesMigrationTableExist>;
const mockedEnsureMigrationTables =
  ensureMigrationTables as jest.MockedFunction<typeof ensureMigrationTables>;
const mockedGetAutoGeneratedCreateTableName =
  getAutoGeneratedCreateTableName as jest.MockedFunction<
    typeof getAutoGeneratedCreateTableName
  >;
const mockedReleaseMigrationLock =
  releaseMigrationLock as jest.MockedFunction<typeof releaseMigrationLock>;
const mockedValidateMigrationHistory =
  validateMigrationHistory as jest.MockedFunction<typeof validateMigrationHistory>;

describe("migrate:rollback smart fallback behavior", () => {
  const originalExistsSync = fs.existsSync;
  const adapter = {
    execute: jest.fn<Promise<void>, [string, unknown[]?]>(),
    wrapId: jest.fn((id: string) => `\`${id}\``),
  };

  beforeEach(() => {
    jest.clearAllMocks();
    process.exitCode = 0;

    mockedGetAdapter.mockResolvedValue(adapter as never);
    mockedCloseAllConnections.mockResolvedValue(undefined);
    mockedEnsureMigrationTables.mockResolvedValue("mysql");
    mockedAcquireMigrationLock.mockResolvedValue(undefined);
    mockedReleaseMigrationLock.mockResolvedValue(undefined);
    mockedValidateMigrationHistory.mockResolvedValue([
      {
        id: 1,
        name: "20260305122614001_create_appsmokes_table.ts",
        batch: 1,
        checksum: "checksum",
      } as never,
    ]);
    mockedGetAutoGeneratedCreateTableName.mockReturnValue("appsmokes");
    mockedDoesMigrationTableExist.mockResolvedValue(true);
    mockedDeleteAppliedMigration.mockResolvedValue(undefined);
    mockedResolveConnectionName.mockReturnValue("mysql" as never);
    adapter.execute.mockResolvedValue(undefined);

    jest.spyOn(console, "log").mockImplementation(() => undefined);
    jest.spyOn(console, "warn").mockImplementation(() => undefined);
    jest.spyOn(console, "error").mockImplementation(() => undefined);

    const migrationsDir = PathMap.migrations(false, "mysql");
    jest.spyOn(fs, "existsSync").mockImplementation((target: fs.PathLike) => {
      const normalized = path.resolve(String(target));
      if (normalized === migrationsDir) {
        return true;
      }
      if (String(target).endsWith("20260305122614001_create_appsmokes_table.ts")) {
        return false;
      }
      return originalExistsSync(target);
    });
  });

  afterEach(() => {
    jest.restoreAllMocks();
    process.exitCode = 0;
  });

  test("drops orphan table and deletes migration row when migration file is missing", async () => {
    await migrateRollback({
      test: false,
      allMigrations: true,
      connectionNames: ["mysql"],
    });

    expect(mockedGetAdapter).toHaveBeenCalledWith("mysql");
    expect(mockedDoesMigrationTableExist).toHaveBeenCalledWith(adapter as never, "appsmokes");
    expect(adapter.execute).toHaveBeenCalledWith("DROP TABLE IF EXISTS `appsmokes`;", []);
    expect(mockedDeleteAppliedMigration).toHaveBeenCalledWith(
      adapter as never,
      "20260305122614001_create_appsmokes_table.ts"
    );
    expect(mockedCloseAllConnections).toHaveBeenCalled();
    expect(process.exitCode).toBe(0);
  });

  test("sets non-zero exit code when rollback down() throws", async () => {
    const failingMigration = "20260305122614002_update_appsmokes_table.ts";
    mockedValidateMigrationHistory.mockResolvedValue([
      {
        id: 2,
        name: failingMigration,
        batch: 1,
        checksum: "checksum",
      } as never,
    ]);
    mockedGetAutoGeneratedCreateTableName.mockReturnValue(null);
    mockedLoadModule.mockReturnValue({
      down: async () => {
        throw new Error("boom");
      },
    } as never);

    const migrationsDir = PathMap.migrations(false, "mysql");
    (fs.existsSync as jest.MockedFunction<typeof fs.existsSync>).mockImplementation(
      (target: fs.PathLike) => {
        const normalized = path.resolve(String(target));
        if (normalized === migrationsDir) {
          return true;
        }
        if (String(target).endsWith(failingMigration)) {
          return true;
        }
        return originalExistsSync(target);
      }
    );

    await migrateRollback({
      test: false,
      allMigrations: true,
      connectionNames: ["mysql"],
    });

    expect(mockedLoadModule).toHaveBeenCalled();
    expect(mockedDeleteAppliedMigration).not.toHaveBeenCalledWith(
      adapter as never,
      failingMigration
    );
    expect(process.exitCode).toBe(1);
  });
});

