import fs from "fs";
import path from "path";
import { PathMap } from "../cli/utils/PathMap";
import { migrateRollback } from "../cli/commands/migrateRollback";
import { migrateRun } from "../cli/commands/migrateRun";
import {
  closeAllConnections,
  getAdapter,
} from "../core/connection/ConnectionFactory";
import { resolveConnectionName } from "../core/connection/resolveConnectionName";
import {
  acquireMigrationLock,
  computeMigrationChecksum,
  deleteAppliedMigration,
  doesMigrationTableExist,
  ensureMigrationTables,
  getAutoGeneratedCreateTableName,
  readLastBatch,
  recordAppliedMigration,
  releaseMigrationLock,
  validateMigrationHistory,
} from "../cli/utils/migrations/MigrationTracker";
import { loadModule } from "../cli/utils/typescript/tsRuntime";

jest.mock("chalk", () => ({
  __esModule: true,
  default: {
    gray: (value: string) => value,
    yellow: (value: string) => value,
    cyan: (value: string) => value,
    green: (value: string) => value,
    greenBright: (value: string) => value,
    red: (value: string) => value,
  },
}));

jest.mock("../core/connection/ConnectionFactory", () => ({
  getAdapter: jest.fn(),
  closeAllConnections: jest.fn(),
}));

jest.mock("../core/connection/resolveConnectionName", () => ({
  resolveConnectionName: jest.fn(),
}));

jest.mock("../cli/utils/migrations/MigrationTracker", () => ({
  acquireMigrationLock: jest.fn(),
  computeMigrationChecksum: jest.fn(),
  deleteAppliedMigration: jest.fn(),
  doesMigrationTableExist: jest.fn(),
  ensureMigrationTables: jest.fn(),
  getAutoGeneratedCreateTableName: jest.fn(),
  readLastBatch: jest.fn(),
  recordAppliedMigration: jest.fn(),
  releaseMigrationLock: jest.fn(),
  validateMigrationHistory: jest.fn(),
}));

jest.mock("../cli/utils/typescript/tsRuntime", () => ({
  loadModule: jest.fn(),
}));

const mockedGetAdapter = getAdapter as jest.MockedFunction<typeof getAdapter>;
const mockedCloseAllConnections =
  closeAllConnections as jest.MockedFunction<typeof closeAllConnections>;
const mockedResolveConnectionName =
  resolveConnectionName as jest.MockedFunction<typeof resolveConnectionName>;
const mockedAcquireMigrationLock =
  acquireMigrationLock as jest.MockedFunction<typeof acquireMigrationLock>;
const mockedComputeMigrationChecksum =
  computeMigrationChecksum as jest.MockedFunction<typeof computeMigrationChecksum>;
const mockedDeleteAppliedMigration =
  deleteAppliedMigration as jest.MockedFunction<typeof deleteAppliedMigration>;
const mockedDoesMigrationTableExist =
  doesMigrationTableExist as jest.MockedFunction<typeof doesMigrationTableExist>;
const mockedEnsureMigrationTables =
  ensureMigrationTables as jest.MockedFunction<typeof ensureMigrationTables>;
const mockedGetAutoGeneratedCreateTableName =
  getAutoGeneratedCreateTableName as jest.MockedFunction<
    typeof getAutoGeneratedCreateTableName
  >;
const mockedReadLastBatch = readLastBatch as jest.MockedFunction<typeof readLastBatch>;
const mockedRecordAppliedMigration =
  recordAppliedMigration as jest.MockedFunction<typeof recordAppliedMigration>;
const mockedReleaseMigrationLock =
  releaseMigrationLock as jest.MockedFunction<typeof releaseMigrationLock>;
const mockedValidateMigrationHistory =
  validateMigrationHistory as jest.MockedFunction<typeof validateMigrationHistory>;
const mockedLoadModule = loadModule as jest.MockedFunction<typeof loadModule>;

describe("migrate rollback partial-recovery workflow", () => {
  const originalExistsSync = fs.existsSync;
  const originalReaddirSync = fs.readdirSync;
  const adapter = {
    execute: jest.fn<Promise<void>, [string, unknown[]?]>(),
    wrapId: jest.fn((id: string) => `\`${id}\``),
    placeholder: jest.fn((index: number) => `?${index}`),
  };

  const connectionName = "mysql";
  const createMigration = "202603070001_create_users_table.ts";
  const updateMigration = "202603070002_update_users_table.ts";
  const migrationsDir = PathMap.migrations(false, connectionName);

  let appliedRows: Array<{ id: number; name: string; batch: number }> = [];
  let createDownFails = true;

  beforeEach(() => {
    jest.clearAllMocks();
    process.exitCode = 0;

    appliedRows = [
      { id: 1, name: createMigration, batch: 1 },
      { id: 2, name: updateMigration, batch: 1 },
    ];
    createDownFails = true;

    mockedGetAdapter.mockResolvedValue(adapter as never);
    mockedCloseAllConnections.mockResolvedValue(undefined);
    mockedResolveConnectionName.mockReturnValue(connectionName as never);
    mockedEnsureMigrationTables.mockResolvedValue("mysql");
    mockedAcquireMigrationLock.mockResolvedValue(undefined);
    mockedReleaseMigrationLock.mockResolvedValue(undefined);
    mockedDoesMigrationTableExist.mockResolvedValue(false);
    mockedGetAutoGeneratedCreateTableName.mockReturnValue(null);
    mockedComputeMigrationChecksum.mockReturnValue("checksum");
    adapter.execute.mockResolvedValue(undefined);

    mockedValidateMigrationHistory.mockImplementation(async () => {
      return appliedRows.map((row) => ({ ...row })) as never;
    });

    mockedDeleteAppliedMigration.mockImplementation(async (_db, fileName) => {
      appliedRows = appliedRows.filter((row) => row.name !== fileName);
    });

    mockedReadLastBatch.mockImplementation(async () => {
      const maxBatch = appliedRows.reduce(
        (max, row) => (row.batch > max ? row.batch : max),
        0
      );
      return maxBatch as never;
    });

    mockedRecordAppliedMigration.mockImplementation(
      async (_db, fileName, batch) => {
        const nextId =
          appliedRows.reduce((max, row) => (row.id > max ? row.id : max), 0) + 1;
        appliedRows.push({
          id: nextId,
          name: fileName,
          batch,
        });
      }
    );

    mockedLoadModule.mockImplementation((modulePath: string) => {
      const fileName = path.basename(modulePath);

      if (fileName === updateMigration) {
        return {
          up: async (db: { query(sql: string, params?: unknown[]): Promise<void> }) => {
            await db.query("ALTER TABLE users ADD COLUMN bio TEXT;");
          },
          down: async (db: { query(sql: string, params?: unknown[]): Promise<void> }) => {
            await db.query("ALTER TABLE users DROP COLUMN bio;");
          },
        } as never;
      }

      if (fileName === createMigration) {
        return {
          up: async (db: { query(sql: string, params?: unknown[]): Promise<void> }) => {
            await db.query("CREATE TABLE users (id INT);");
          },
          down: async (db: { query(sql: string, params?: unknown[]): Promise<void> }) => {
            if (createDownFails) {
              throw new Error("create rollback failed");
            }
            await db.query("DROP TABLE users;");
          },
        } as never;
      }

      return {} as never;
    });

    jest.spyOn(console, "log").mockImplementation(() => undefined);
    jest.spyOn(console, "warn").mockImplementation(() => undefined);
    jest.spyOn(console, "error").mockImplementation(() => undefined);

    jest.spyOn(fs, "existsSync").mockImplementation((target: fs.PathLike) => {
      const normalized = path.resolve(String(target));
      if (normalized === path.resolve(migrationsDir)) return true;
      if (normalized.endsWith(createMigration)) return true;
      if (normalized.endsWith(updateMigration)) return true;
      return originalExistsSync(target);
    });

    jest.spyOn(fs, "readdirSync").mockImplementation((target: fs.PathLike) => {
      if (path.resolve(String(target)) === path.resolve(migrationsDir)) {
        return [createMigration, updateMigration] as unknown as ReturnType<
          typeof fs.readdirSync
        >;
      }
      return originalReaddirSync(target) as unknown as ReturnType<
        typeof fs.readdirSync
      >;
    });
  });

  afterEach(() => {
    jest.restoreAllMocks();
    process.exitCode = 0;
  });

  test("operator can recover from partial rollback failure and re-apply migrations", async () => {
    await migrateRollback({
      test: false,
      allMigrations: true,
      connectionNames: [connectionName],
    });

    expect(process.exitCode).toBe(1);
    expect(appliedRows.map((row) => row.name).sort()).toEqual([createMigration]);
    expect(mockedDeleteAppliedMigration).toHaveBeenCalledWith(
      adapter as never,
      updateMigration
    );

    process.exitCode = 0;
    createDownFails = false;

    await migrateRollback({
      test: false,
      allMigrations: true,
      connectionNames: [connectionName],
    });

    expect(process.exitCode).toBe(0);
    expect(appliedRows).toEqual([]);

    process.exitCode = 0;

    await migrateRun(false, undefined, false, false, {
      connectionNames: [connectionName],
    });

    expect(process.exitCode).toBe(0);
    expect(appliedRows.map((row) => row.name).sort()).toEqual([
      createMigration,
      updateMigration,
    ]);
    expect(mockedRecordAppliedMigration).toHaveBeenCalledTimes(2);
    expect(mockedCloseAllConnections).toHaveBeenCalled();
  });
});

