/**
 * 🧱 Migration: create_users_table
 * Generated by EloquentJS Artisan v2.0
 * Date: 2025-10-26
 */

export async function up(db: DatabaseConnection) {
  interface TableBuilder {
    increments(column: string): this;
    primary(): this;
    string(column: string): this;
    unique?(): this;
    timestamp?(column: string): this;
    timestamps?(useTz?: boolean, defaultNow?: boolean): this;
  }

  await db.schema.createTable<TableBuilder>("users", (table) => {
    table.increments("id").primary();
    table.string("name");
    // Add more columns here...
  });
}

export async function down(db: DatabaseConnection) {
  await db.schema.dropTableIfExists("users");
}

/**
 * 🧩 Local types (self-contained, no globals)
 */
interface SchemaBuilder {
  createTable<T>(name: string, callback: (table: T) => void): Promise<void>;
  dropTableIfExists(name: string): Promise<void>;
}

interface DatabaseConnection {
  schema: SchemaBuilder;
  fn: { now(): string | Date };
}
