import fs from "fs";
import path from "path";
import chalk from "chalk";
import { getAdapter, closeAllConnections, ConnectionName } from "../../core/connection/ConnectionFactory";
import { PathMap } from "../utils/PathMap";
import { dbConfig } from "../../config/database";
import { resolveConnectionName } from "../../core/connection/resolveConnectionName";
import {
  acquireMigrationLock,
  doesMigrationTableExist,
  deleteAppliedMigration,
  ensureMigrationTables,
  getAutoGeneratedCreateTableName,
  releaseMigrationLock,
  validateMigrationHistory,
} from "../utils/migrations/MigrationTracker";
import { loadModule } from "../utils/typescript/tsRuntime";
import { appendAuditEvent } from "../utils/AuditTrail";

export type MigrateRollbackOptions = {
  test?: boolean;
  step?: number;
  connectionNames?: ConnectionName[];
  allMigrations?: boolean;
  auditCommand?: string;
};

async function rollbackConnection(
  connectionName: ConnectionName,
  isTest: boolean,
  step: number
): Promise<boolean> {
  const stepLabel = step === Number.MAX_SAFE_INTEGER ? "all" : String(step);

  console.log(
    chalk.cyan(
      `\nRolling back migrations in ${isTest ? "TEST" : "DEVELOPMENT"} mode on "${connectionName}" (step ${stepLabel})...\n`
    )
  );

  const migrationsDir = PathMap.migrations(isTest, connectionName);
  if (!fs.existsSync(migrationsDir)) {
    console.log(chalk.yellow(`No migrations directory found for ${connectionName}.`));
    return true;
  }

  const driver = dbConfig.connections[connectionName]?.driver ?? connectionName;
  if (!driver || !["mysql", "pg", "sqlite"].includes(driver)) {
    console.warn(chalk.yellow(`Rollback skipped: "${connectionName}" is not SQL-based.`));
    return true;
  }

  const db = await getAdapter(connectionName);
  console.log(chalk.gray(`Connected to ${connectionName}.`));
  const lockOwner = `migrate:rollback:${connectionName}:${process.pid}:${Date.now()}`;

  const runQuery = async (sql: string, params: unknown[] = []): Promise<void> => {
    await db.execute(sql, params);
  };

  let lockAcquired = false;
  let completedWithoutError = false;

  try {
    await ensureMigrationTables(db);
    await acquireMigrationLock(db, lockOwner);
    lockAcquired = true;

    let rows: { id?: number; name: string; batch: number }[] = [];
    rows = (await validateMigrationHistory(db, migrationsDir))
      .map((row) => ({ id: row.id, name: row.name, batch: row.batch }))
      .sort((a, b) => {
        if (b.batch !== a.batch) return b.batch - a.batch;
        return (b.id ?? 0) - (a.id ?? 0);
      });

    if (rows.length === 0) {
      console.log(chalk.yellow("No migrations found to roll back."));
      completedWithoutError = true;
      return true;
    }

    const targetBatches = Array.from(new Set(rows.map((r) => r.batch))).slice(0, step);
    const toRollback = rows.filter((r) => targetBatches.includes(r.batch));

    if (toRollback.length === 0) {
      console.log(chalk.yellow("Nothing to roll back."));
      completedWithoutError = true;
      return true;
    }

    console.log(chalk.gray(`Rolling back ${toRollback.length} migration(s)...`));

    let rolledBack = 0;
    let hadRollbackError = false;
    for (const entry of toRollback) {
      const migrationFile = entry.name;
      const filePath = path.join(migrationsDir, migrationFile);

      if (!fs.existsSync(filePath)) {
        const fallbackTable = getAutoGeneratedCreateTableName(migrationFile);
        if (fallbackTable) {
          try {
            const exists = await doesMigrationTableExist(db, fallbackTable);
            if (exists) {
              const dropSql =
                driver === "pg"
                  ? `DROP TABLE IF EXISTS ${db.wrapId(fallbackTable)} CASCADE;`
                  : `DROP TABLE IF EXISTS ${db.wrapId(fallbackTable)};`;
              await runQuery(dropSql);
              console.log(
                chalk.yellow(
                  `Fallback rollback: dropped table "${fallbackTable}" for missing migration file "${migrationFile}".`
                )
              );
            } else {
              console.log(
                chalk.yellow(
                  `Fallback rollback: table "${fallbackTable}" already absent for missing migration file "${migrationFile}".`
                )
              );
            }
            await deleteAppliedMigration(db, migrationFile);
            rolledBack++;
            continue;
          } catch (fallbackError) {
            console.error(chalk.red(`Fallback rollback failed for ${migrationFile}:`));
            console.error(fallbackError);
            hadRollbackError = true;
            break;
          }
        }

        console.error(chalk.red(`Missing file: ${migrationFile}`));
        hadRollbackError = true;
        break;
      }

      try {
        const migrationModule = loadModule(path.resolve(filePath)) as {
          down?: (db: { query(sql: string, params?: unknown[]): Promise<void> }) => Promise<void>;
        };

        if (typeof migrationModule.down !== "function") {
          console.log(chalk.gray(`No down() method: ${migrationFile}`));
          continue;
        }

        console.log(chalk.gray(`Reverting: ${migrationFile}`));
        await migrationModule.down({ query: runQuery });

        await deleteAppliedMigration(db, migrationFile);
        console.log(chalk.green(`Rolled back: ${migrationFile}`));
        rolledBack++;
      } catch (err) {
        console.error(chalk.red(`Error rolling back ${migrationFile}:`));
        console.error(err);
        hadRollbackError = true;
        break;
      }
    }

    console.log(chalk.greenBright(`\n${rolledBack} migration(s) rolled back successfully.\n`));
    completedWithoutError = !hadRollbackError;
    return !hadRollbackError;
  } catch (err) {
    console.error(chalk.red("Unable to read or validate migrations table."));
    console.error(err);
    return false;
  } finally {
    if (lockAcquired) {
      await releaseMigrationLock(db, lockOwner, { success: completedWithoutError });
    }
    await closeAllConnections();
    console.log(chalk.gray("All database connections closed.\n"));
  }
}

export async function migrateRollback(
  options: MigrateRollbackOptions = {}
): Promise<void> {
  const isTest = !!options.test;
  const step = options.allMigrations
    ? Number.MAX_SAFE_INTEGER
    : Math.max(1, Number(options.step || 1));

  const connectionNames =
    options.connectionNames && options.connectionNames.length > 0
      ? options.connectionNames
      : [resolveConnectionName(undefined, { test: isTest })];

  let hadFailure = false;
  const auditCommand = options.auditCommand ?? "migrate:rollback";
  for (const connectionName of connectionNames) {
    const success = await rollbackConnection(connectionName, isTest, step);
    appendAuditEvent({
      command: auditCommand,
      connectionName,
      test: isTest,
      result: success ? "success" : "failure",
      metadata: {
        step,
        allMigrations: options.allMigrations === true,
      },
    });
    if (!success) {
      hadFailure = true;
    }
  }

  if (hadFailure) {
    process.exitCode = 1;
  }
}
